//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lite.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lite.Resources.Localization.ApplicationResources", typeof(ApplicationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Layer.
        /// </summary>
        public static string AddLayer {
            get {
                return ResourceManager.GetString("AddLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Query.
        /// </summary>
        public static string AddQuery {
            get {
                return ResourceManager.GetString("AddQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        public static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Selection.
        /// </summary>
        public static string ClearSelection {
            get {
                return ResourceManager.GetString("ClearSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Trail.
        /// </summary>
        public static string ClearTrail {
            get {
                return ResourceManager.GetString("ClearTrail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CopyToClipboardCancel {
            get {
                return ResourceManager.GetString("CopyToClipboardCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string CopyToClipboardOK {
            get {
                return ResourceManager.GetString("CopyToClipboardOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Query Results.
        /// </summary>
        public static string ExportQueryResults {
            get {
                return ResourceManager.GetString("ExportQueryResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Settings.
        /// </summary>
        public static string ExportSettings {
            get {
                return ResourceManager.GetString("ExportSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Line.
        /// </summary>
        public static string ExpressionAddLine {
            get {
                return ResourceManager.GetString("ExpressionAddLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field.
        /// </summary>
        public static string ExpressionBuilderFieldColumn {
            get {
                return ResourceManager.GetString("ExpressionBuilderFieldColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        public static string ExpressionBuilderOperatorColumn {
            get {
                return ResourceManager.GetString("ExpressionBuilderOperatorColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string ExpressionBuilderValueColumn {
            get {
                return ResourceManager.GetString("ExpressionBuilderValueColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Line.
        /// </summary>
        public static string ExpressionRemoveLine {
            get {
                return ResourceManager.GetString("ExpressionRemoveLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string FeatureDetails {
            get {
                return ResourceManager.GetString("FeatureDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach new {0}.
        /// </summary>
        public static string FeatureDetailsAttachNewItem {
            get {
                return ResourceManager.GetString("FeatureDetailsAttachNewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Feature.
        /// </summary>
        public static string FeatureDetailsGettingFeature {
            get {
                return ResourceManager.GetString("FeatureDetailsGettingFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Features.
        /// </summary>
        public static string FeatureDetailsMultipleFeatures {
            get {
                return ResourceManager.GetString("FeatureDetailsMultipleFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Area.
        /// </summary>
        public static string FeatureDetailsMultipleFeaturesArea {
            get {
                return ResourceManager.GetString("FeatureDetailsMultipleFeaturesArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Length.
        /// </summary>
        public static string FeatureDetailsMultipleFeaturesLength {
            get {
                return ResourceManager.GetString("FeatureDetailsMultipleFeaturesLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elements.
        /// </summary>
        public static string FeatureDetailsMultipleFeaturesNumberOfElements {
            get {
                return ResourceManager.GetString("FeatureDetailsMultipleFeaturesNumberOfElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Feature from the Map.
        /// </summary>
        public static string FeatureDetailsSelectFeatureFromMap {
            get {
                return ResourceManager.GetString("FeatureDetailsSelectFeatureFromMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert GeoNote.
        /// </summary>
        public static string FeatureEditInsertCategoryHeader {
            get {
                return ResourceManager.GetString("FeatureEditInsertCategoryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving Collection.
        /// </summary>
        public static string FeatureResultListRetrievingCollection {
            get {
                return ResourceManager.GetString("FeatureResultListRetrievingCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Place.
        /// </summary>
        public static string GeoLocatorEmptyRequest {
            get {
                return ResourceManager.GetString("GeoLocatorEmptyRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert GeoNote.
        /// </summary>
        public static string GeoNoteInsert {
            get {
                return ResourceManager.GetString("GeoNoteInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Home View.
        /// </summary>
        public static string GotoHomeView {
            get {
                return ResourceManager.GetString("GotoHomeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Selection.
        /// </summary>
        public static string GotoSelection {
            get {
                return ResourceManager.GetString("GotoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string HeterogeneousMainCollectionDescription {
            get {
                return ResourceManager.GetString("HeterogeneousMainCollectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string HeterogeneousSubCollectionDescription {
            get {
                return ResourceManager.GetString("HeterogeneousSubCollectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight Selection in Map.
        /// </summary>
        public static string HighlightSelectionInMap {
            get {
                return ResourceManager.GetString("HighlightSelectionInMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layers.
        /// </summary>
        public static string Layers {
            get {
                return ResourceManager.GetString("Layers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider.
        /// </summary>
        public static string LayersNewLayerServiceProvider {
            get {
                return ResourceManager.GetString("LayersNewLayerServiceProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string LayersNewLayerServiceProviderGroupType {
            get {
                return ResourceManager.GetString("LayersNewLayerServiceProviderGroupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer.
        /// </summary>
        public static string LayersNewLayerServiceProviderLayer {
            get {
                return ResourceManager.GetString("LayersNewLayerServiceProviderLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Mode.
        /// </summary>
        public static string MapDefaultMode {
            get {
                return ResourceManager.GetString("MapDefaultMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to Geographic Map.
        /// </summary>
        public static string MapGoToPreviousWorld {
            get {
                return ResourceManager.GetString("MapGoToPreviousWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Layers.
        /// </summary>
        public static string MapLayersDescriptionFormat {
            get {
                return ResourceManager.GetString("MapLayersDescriptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orthogonal.
        /// </summary>
        public static string MapMeasureDimMode {
            get {
                return ResourceManager.GetString("MapMeasureDimMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measuring (Orthogonal) using WGS84 coordinate system.
        /// </summary>
        public static string MapMeasureDimModeDescription {
            get {
                return ResourceManager.GetString("MapMeasureDimModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure.
        /// </summary>
        public static string MapMeasureFreeMode {
            get {
                return ResourceManager.GetString("MapMeasureFreeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measuring using WGS84 coordinate system.
        /// </summary>
        public static string MapMeasureFreeModeDescription {
            get {
                return ResourceManager.GetString("MapMeasureFreeModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurer.
        /// </summary>
        public static string MapMeasurer {
            get {
                return ResourceManager.GetString("MapMeasurer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure Mode.
        /// </summary>
        public static string MapMeasurerModeCategoryHeader {
            get {
                return ResourceManager.GetString("MapMeasurerModeCategoryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Selection.
        /// </summary>
        public static string MapPopupClearSelection {
            get {
                return ResourceManager.GetString("MapPopupClearSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Coordinate.
        /// </summary>
        public static string MapPopupCopyCoordinateToClipboard {
            get {
                return ResourceManager.GetString("MapPopupCopyCoordinateToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Trail from Selection.
        /// </summary>
        public static string MapPopupCreateTrailFromSelection {
            get {
                return ResourceManager.GetString("MapPopupCreateTrailFromSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Selected Geometry.
        /// </summary>
        public static string MapPopupEditGeometrySelection {
            get {
                return ResourceManager.GetString("MapPopupEditGeometrySelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Selected Features.
        /// </summary>
        public static string MapPopupGotoSelection {
            get {
                return ResourceManager.GetString("MapPopupGotoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Properties.
        /// </summary>
        public static string MapPopupObjectProperties {
            get {
                return ResourceManager.GetString("MapPopupObjectProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Trail.
        /// </summary>
        public static string MapPopupRemoveTrail {
            get {
                return ResourceManager.GetString("MapPopupRemoveTrail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the Map &apos;{0}&apos;?.
        /// </summary>
        public static string MapRemoveStringFormat {
            get {
                return ResourceManager.GetString("MapRemoveStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Map?.
        /// </summary>
        public static string MapRemoveTitle {
            get {
                return ResourceManager.GetString("MapRemoveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maps.
        /// </summary>
        public static string Maps {
            get {
                return ResourceManager.GetString("Maps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Map.
        /// </summary>
        public static string MapsAddMap {
            get {
                return ResourceManager.GetString("MapsAddMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider.
        /// </summary>
        public static string MapsNewMapServiceProvider {
            get {
                return ResourceManager.GetString("MapsNewMapServiceProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string MapsNewMapServiceProviderGroupType {
            get {
                return ResourceManager.GetString("MapsNewMapServiceProviderGroupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base On.
        /// </summary>
        public static string MapsNewMapServiceProviderMap {
            get {
                return ResourceManager.GetString("MapsNewMapServiceProviderMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trail.
        /// </summary>
        public static string MapTrail {
            get {
                return ResourceManager.GetString("MapTrail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trail Actions.
        /// </summary>
        public static string MapTrailActionsCategoryHeader {
            get {
                return ResourceManager.GetString("MapTrailActionsCategoryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        public static string MapTrailClearAll {
            get {
                return ResourceManager.GetString("MapTrailClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Trail.
        /// </summary>
        public static string MapTrailCreateCategoryHeader {
            get {
                return ResourceManager.GetString("MapTrailCreateCategoryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string MessageBoxCancel {
            get {
                return ResourceManager.GetString("MessageBoxCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string MessageBoxOK {
            get {
                return ResourceManager.GetString("MessageBoxOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No server address has been specified in the html page of the application.
        /// </summary>
        public static string NoServerAddressInHtmlPage {
            get {
                return ResourceManager.GetString("NoServerAddressInHtmlPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Server Address Found.
        /// </summary>
        public static string NoServerAddressInHtmlPageTitle {
            get {
                return ResourceManager.GetString("NoServerAddressInHtmlPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide the mini map.
        /// </summary>
        public static string OverviewMapHide {
            get {
                return ResourceManager.GetString("OverviewMapHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See the mini map.
        /// </summary>
        public static string OverviewMapShow {
            get {
                return ResourceManager.GetString("OverviewMapShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshot.
        /// </summary>
        public static string PlaceFinderSnapShot {
            get {
                return ResourceManager.GetString("PlaceFinderSnapShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Default Template.
        /// </summary>
        public static string PrintTemplateDefault {
            get {
                return ResourceManager.GetString("PrintTemplateDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default print template.
        /// </summary>
        public static string PrintTemplateDefaultDescription {
            get {
                return ResourceManager.GetString("PrintTemplateDefaultDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Legend Template.
        /// </summary>
        public static string PrintTemplateDefaultWithLegend {
            get {
                return ResourceManager.GetString("PrintTemplateDefaultWithLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template with legend.
        /// </summary>
        public static string PrintTemplateDefaultWithLegendDescription {
            get {
                return ResourceManager.GetString("PrintTemplateDefaultWithLegendDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Legend.
        /// </summary>
        public static string PrintTemplateLegendOnly {
            get {
                return ResourceManager.GetString("PrintTemplateLegendOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template with legend only.
        /// </summary>
        public static string PrintTemplateLegendOnlyDescription {
            get {
                return ResourceManager.GetString("PrintTemplateLegendOnlyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queries.
        /// </summary>
        public static string Queries {
            get {
                return ResourceManager.GetString("Queries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider.
        /// </summary>
        public static string QueriesNewQueryTableServiceProvider {
            get {
                return ResourceManager.GetString("QueriesNewQueryTableServiceProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string QueriesNewQueryTableServiceProviderGroup {
            get {
                return ResourceManager.GetString("QueriesNewQueryTableServiceProviderGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string QueriesNewQueryTableServiceProviderGroupType {
            get {
                return ResourceManager.GetString("QueriesNewQueryTableServiceProviderGroupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string QueriesNewQueryTableServiceProviderTable {
            get {
                return ResourceManager.GetString("QueriesNewQueryTableServiceProviderTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        public static string Query {
            get {
                return ResourceManager.GetString("Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Export.
        /// </summary>
        public static string QueryCreatingExport {
            get {
                return ResourceManager.GetString("QueryCreatingExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Report.
        /// </summary>
        public static string QueryCreatingReport {
            get {
                return ResourceManager.GetString("QueryCreatingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the Query &apos;{0}&apos;?.
        /// </summary>
        public static string QueryRemoveStringFormat {
            get {
                return ResourceManager.GetString("QueryRemoveStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Query?.
        /// </summary>
        public static string QueryRemoveTitle {
            get {
                return ResourceManager.GetString("QueryRemoveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a curve from the map.
        /// </summary>
        public static string QuerySelectCurveFromMap {
            get {
                return ResourceManager.GetString("QuerySelectCurveFromMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a geometry from the map.
        /// </summary>
        public static string QuerySelectGeometryFromMap {
            get {
                return ResourceManager.GetString("QuerySelectGeometryFromMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a point from the map.
        /// </summary>
        public static string QuerySelectPointFromMap {
            get {
                return ResourceManager.GetString("QuerySelectPointFromMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a polygon from the map.
        /// </summary>
        public static string QuerySelectPolygonFromMap {
            get {
                return ResourceManager.GetString("QuerySelectPolygonFromMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Builder.
        /// </summary>
        public static string QueryViaExpressionBuilder {
            get {
                return ResourceManager.GetString("QueryViaExpressionBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Query.
        /// </summary>
        public static string RemoveQuery {
            get {
                return ResourceManager.GetString("RemoveQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Query Results.
        /// </summary>
        public static string ReportQueryResults {
            get {
                return ResourceManager.GetString("ReportQueryResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Query.
        /// </summary>
        public static string RunQuery {
            get {
                return ResourceManager.GetString("RunQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Query.
        /// </summary>
        public static string SaveQuery {
            get {
                return ResourceManager.GetString("SaveQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Favorites.
        /// </summary>
        public static string ShowFavorites {
            get {
                return ResourceManager.GetString("ShowFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street View.
        /// </summary>
        public static string StreetView {
            get {
                return ResourceManager.GetString("StreetView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Scalebar.
        /// </summary>
        public static string SwitchScaleBar {
            get {
                return ResourceManager.GetString("SwitchScaleBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Units.
        /// </summary>
        public static string SwitchUnits {
            get {
                return ResourceManager.GetString("SwitchUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Selection in Details.
        /// </summary>
        public static string TrackSelectionInDetails {
            get {
                return ResourceManager.GetString("TrackSelectionInDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Selection in Map.
        /// </summary>
        public static string TrackSelectionInMap {
            get {
                return ResourceManager.GetString("TrackSelectionInMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle.
        /// </summary>
        public static string TrailCircle {
            get {
                return ResourceManager.GetString("TrailCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curve.
        /// </summary>
        public static string TrailCurve {
            get {
                return ResourceManager.GetString("TrailCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point.
        /// </summary>
        public static string TrailPoint {
            get {
                return ResourceManager.GetString("TrailPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polygon.
        /// </summary>
        public static string TrailPolygon {
            get {
                return ResourceManager.GetString("TrailPolygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle.
        /// </summary>
        public static string TrailRectangle {
            get {
                return ResourceManager.GetString("TrailRectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Failed.
        /// </summary>
        public static string TransactionDeleteFailedCaption {
            get {
                return ResourceManager.GetString("TransactionDeleteFailedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting the feature failed.
        /// </summary>
        public static string TransactionDeleteFailedMessage {
            get {
                return ResourceManager.GetString("TransactionDeleteFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Feature.
        /// </summary>
        public static string TransactionDeleteQuestionCaption {
            get {
                return ResourceManager.GetString("TransactionDeleteQuestionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the feature?.
        /// </summary>
        public static string TransactionDeleteQuestionMessage {
            get {
                return ResourceManager.GetString("TransactionDeleteQuestionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Failed.
        /// </summary>
        public static string TransactionInsertFailedCaption {
            get {
                return ResourceManager.GetString("TransactionInsertFailedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserting the feature failed.
        /// </summary>
        public static string TransactionInsertFailedMessage {
            get {
                return ResourceManager.GetString("TransactionInsertFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Failed.
        /// </summary>
        public static string TransactionUpdateFailedCaption {
            get {
                return ResourceManager.GetString("TransactionUpdateFailedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating the feature failed.
        /// </summary>
        public static string TransactionUpdateFailedMessage {
            get {
                return ResourceManager.GetString("TransactionUpdateFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear geometry.
        /// </summary>
        public static string TypedValueGeometryControlClearToolTip {
            get {
                return ResourceManager.GetString("TypedValueGeometryControlClearToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set from selection.
        /// </summary>
        public static string TypedValueGeometryControlCopyToolTip {
            get {
                return ResourceManager.GetString("TypedValueGeometryControlCopyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit geometry.
        /// </summary>
        public static string TypedValueGeometryControlEditToolTip {
            get {
                return ResourceManager.GetString("TypedValueGeometryControlEditToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear join.
        /// </summary>
        public static string TypedValueJoinControlClearToolTip {
            get {
                return ResourceManager.GetString("TypedValueJoinControlClearToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set from selection.
        /// </summary>
        public static string TypedValueJoinControlCopyToolTip {
            get {
                return ResourceManager.GetString("TypedValueJoinControlCopyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ValueActivationCancel {
            get {
                return ResourceManager.GetString("ValueActivationCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump to.
        /// </summary>
        public static string ValueActivationSelectValue {
            get {
                return ResourceManager.GetString("ValueActivationSelectValue", resourceCulture);
            }
        }
    }
}
