//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace Lite.ServiceGestionCuentas {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.grr.net.fv/svc", ConfigurationName="ServiceGestionCuentas.WsGestionaInfoCuentasPortType")]
    public interface WsGestionaInfoCuentasPortType {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:gestionaCuenta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BegingestionaCuenta(Lite.ServiceGestionCuentas.gestionaCuentaRequest request, System.AsyncCallback callback, object asyncState);
        
        Lite.ServiceGestionCuentas.gestionaCuentaResponse EndgestionaCuenta(System.IAsyncResult result);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="WsGestionaInfoCuentas-RQ-Type", Namespace="http://www.grr.net.fv/gis")]
    public partial class WsGestionaInfoCuentasRQType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string id_cajaField;
        
        private string cuentaField;
        
        private string operacionField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string id_caja {
            get {
                return this.id_cajaField;
            }
            set {
                this.id_cajaField = value;
                this.RaisePropertyChanged("id_caja");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string cuenta {
            get {
                return this.cuentaField;
            }
            set {
                this.cuentaField = value;
                this.RaisePropertyChanged("cuenta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string operacion {
            get {
                return this.operacionField;
            }
            set {
                this.operacionField = value;
                this.RaisePropertyChanged("operacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.grr.net.fv/gis")]
    public partial class detallerespuestatype : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fechaRespuestaField;
        
        private string codigoRespuestaField;
        
        private string codigoErrorField;
        
        private string descripcionErrorField;
        
        private string mensajeErrorField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FechaRespuesta {
            get {
                return this.fechaRespuestaField;
            }
            set {
                this.fechaRespuestaField = value;
                this.RaisePropertyChanged("FechaRespuesta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CodigoRespuesta {
            get {
                return this.codigoRespuestaField;
            }
            set {
                this.codigoRespuestaField = value;
                this.RaisePropertyChanged("CodigoRespuesta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CodigoError {
            get {
                return this.codigoErrorField;
            }
            set {
                this.codigoErrorField = value;
                this.RaisePropertyChanged("CodigoError");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DescripcionError {
            get {
                return this.descripcionErrorField;
            }
            set {
                this.descripcionErrorField = value;
                this.RaisePropertyChanged("DescripcionError");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string MensajeError {
            get {
                return this.mensajeErrorField;
            }
            set {
                this.mensajeErrorField = value;
                this.RaisePropertyChanged("MensajeError");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.grr.net.fv/gis")]
    public partial class InfoCuenta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string estadoField;
        
        private detallerespuestatype detalle_RespuestaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public detallerespuestatype Detalle_Respuesta {
            get {
                return this.detalle_RespuestaField;
            }
            set {
                this.detalle_RespuestaField = value;
                this.RaisePropertyChanged("Detalle_Respuesta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class gestionaCuentaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WsGestionaInfoCuentas-RQ", Namespace="http://www.grr.net.fv/gis", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("WsGestionaInfoCuentas-RQ")]
        public Lite.ServiceGestionCuentas.WsGestionaInfoCuentasRQType WsGestionaInfoCuentasRQ;
        
        public gestionaCuentaRequest() {
        }
        
        public gestionaCuentaRequest(Lite.ServiceGestionCuentas.WsGestionaInfoCuentasRQType WsGestionaInfoCuentasRQ) {
            this.WsGestionaInfoCuentasRQ = WsGestionaInfoCuentasRQ;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class gestionaCuentaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WsGestionaInfoCuentas-RS", Namespace="http://www.grr.net.fv/gis", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("WsGestionaInfoCuentas-RS")]
        public Lite.ServiceGestionCuentas.InfoCuenta WsGestionaInfoCuentasRS;
        
        public gestionaCuentaResponse() {
        }
        
        public gestionaCuentaResponse(Lite.ServiceGestionCuentas.InfoCuenta WsGestionaInfoCuentasRS) {
            this.WsGestionaInfoCuentasRS = WsGestionaInfoCuentasRS;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WsGestionaInfoCuentasPortTypeChannel : Lite.ServiceGestionCuentas.WsGestionaInfoCuentasPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class gestionaCuentaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public gestionaCuentaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Lite.ServiceGestionCuentas.gestionaCuentaResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Lite.ServiceGestionCuentas.gestionaCuentaResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsGestionaInfoCuentasPortTypeClient : System.ServiceModel.ClientBase<Lite.ServiceGestionCuentas.WsGestionaInfoCuentasPortType>, Lite.ServiceGestionCuentas.WsGestionaInfoCuentasPortType {
        
        private BeginOperationDelegate onBegingestionaCuentaDelegate;
        
        private EndOperationDelegate onEndgestionaCuentaDelegate;
        
        private System.Threading.SendOrPostCallback ongestionaCuentaCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public WsGestionaInfoCuentasPortTypeClient() {
        }
        
        public WsGestionaInfoCuentasPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsGestionaInfoCuentasPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsGestionaInfoCuentasPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsGestionaInfoCuentasPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("No se puede establecer el objeto CookieContainer. Asegúrese de que el enlace cont" +
                            "iene un objeto HttpCookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<gestionaCuentaCompletedEventArgs> gestionaCuentaCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Lite.ServiceGestionCuentas.WsGestionaInfoCuentasPortType.BegingestionaCuenta(Lite.ServiceGestionCuentas.gestionaCuentaRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingestionaCuenta(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lite.ServiceGestionCuentas.gestionaCuentaResponse Lite.ServiceGestionCuentas.WsGestionaInfoCuentasPortType.EndgestionaCuenta(System.IAsyncResult result) {
            return base.Channel.EndgestionaCuenta(result);
        }
        
        private System.IAsyncResult OnBegingestionaCuenta(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Lite.ServiceGestionCuentas.gestionaCuentaRequest request = ((Lite.ServiceGestionCuentas.gestionaCuentaRequest)(inValues[0]));
            return ((Lite.ServiceGestionCuentas.WsGestionaInfoCuentasPortType)(this)).BegingestionaCuenta(request, callback, asyncState);
        }
        
        private object[] OnEndgestionaCuenta(System.IAsyncResult result) {
            Lite.ServiceGestionCuentas.gestionaCuentaResponse retVal = ((Lite.ServiceGestionCuentas.WsGestionaInfoCuentasPortType)(this)).EndgestionaCuenta(result);
            return new object[] {
                    retVal};
        }
        
        private void OngestionaCuentaCompleted(object state) {
            if ((this.gestionaCuentaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.gestionaCuentaCompleted(this, new gestionaCuentaCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void gestionaCuentaAsync(Lite.ServiceGestionCuentas.gestionaCuentaRequest request) {
            this.gestionaCuentaAsync(request, null);
        }
        
        public void gestionaCuentaAsync(Lite.ServiceGestionCuentas.gestionaCuentaRequest request, object userState) {
            if ((this.onBegingestionaCuentaDelegate == null)) {
                this.onBegingestionaCuentaDelegate = new BeginOperationDelegate(this.OnBegingestionaCuenta);
            }
            if ((this.onEndgestionaCuentaDelegate == null)) {
                this.onEndgestionaCuentaDelegate = new EndOperationDelegate(this.OnEndgestionaCuenta);
            }
            if ((this.ongestionaCuentaCompletedDelegate == null)) {
                this.ongestionaCuentaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngestionaCuentaCompleted);
            }
            base.InvokeAsync(this.onBegingestionaCuentaDelegate, new object[] {
                        request}, this.onEndgestionaCuentaDelegate, this.ongestionaCuentaCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Lite.ServiceGestionCuentas.WsGestionaInfoCuentasPortType CreateChannel() {
            return new WsGestionaInfoCuentasPortTypeClientChannel(this);
        }
        
        private class WsGestionaInfoCuentasPortTypeClientChannel : ChannelBase<Lite.ServiceGestionCuentas.WsGestionaInfoCuentasPortType>, Lite.ServiceGestionCuentas.WsGestionaInfoCuentasPortType {
            
            public WsGestionaInfoCuentasPortTypeClientChannel(System.ServiceModel.ClientBase<Lite.ServiceGestionCuentas.WsGestionaInfoCuentasPortType> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BegingestionaCuenta(Lite.ServiceGestionCuentas.gestionaCuentaRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("gestionaCuenta", _args, callback, asyncState);
                return _result;
            }
            
            public Lite.ServiceGestionCuentas.gestionaCuentaResponse EndgestionaCuenta(System.IAsyncResult result) {
                object[] _args = new object[0];
                Lite.ServiceGestionCuentas.gestionaCuentaResponse _result = ((Lite.ServiceGestionCuentas.gestionaCuentaResponse)(base.EndInvoke("gestionaCuenta", _args, result)));
                return _result;
            }
        }
    }
}
