//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18063
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace Lite.ServiceEliminaProspecto
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://www.grr.net.fv/svc", ConfigurationName = "ServiceEliminaProspecto.WsEliminaUbicacionProspectoFVPortType")]
    public interface WsEliminaUbicacionProspectoFVPortType
    {

        [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "urn:eliminaUbicacionProspectoFV", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.IAsyncResult BegineliminaUbicacionProspectoFV(Lite.ServiceEliminaProspecto.eliminaUbicacionProspectoFVRequest request, System.AsyncCallback callback, object asyncState);

        Lite.ServiceEliminaProspecto.eliminaUbicacionProspectoFVResponse EndeliminaUbicacionProspectoFV(System.IAsyncResult result);
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "wsEliminaUbicacionProspectoFV-RQ-Type", Namespace = "http://www.grr.net.fv/gis")]
    public partial class wsEliminaUbicacionProspectoFVRQType : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string idSwField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 0)]
        public string idSw
        {
            get
            {
                return this.idSwField;
            }
            set
            {
                this.idSwField = value;
                this.RaisePropertyChanged("idSw");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.grr.net.fv/gis")]
    public partial class detallerespuestatype : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string fechaRespuestaField;

        private string codigoRespuestaField;

        private string codigoErrorField;

        private string descripcionErrorField;

        private string mensajeErrorField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string FechaRespuesta
        {
            get
            {
                return this.fechaRespuestaField;
            }
            set
            {
                this.fechaRespuestaField = value;
                this.RaisePropertyChanged("FechaRespuesta");
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string CodigoRespuesta
        {
            get
            {
                return this.codigoRespuestaField;
            }
            set
            {
                this.codigoRespuestaField = value;
                this.RaisePropertyChanged("CodigoRespuesta");
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string CodigoError
        {
            get
            {
                return this.codigoErrorField;
            }
            set
            {
                this.codigoErrorField = value;
                this.RaisePropertyChanged("CodigoError");
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string DescripcionError
        {
            get
            {
                return this.descripcionErrorField;
            }
            set
            {
                this.descripcionErrorField = value;
                this.RaisePropertyChanged("DescripcionError");
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string MensajeError
        {
            get
            {
                return this.mensajeErrorField;
            }
            set
            {
                this.mensajeErrorField = value;
                this.RaisePropertyChanged("MensajeError");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.grr.net.fv/gis")]
    public partial class InfoProspecto : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string estadoField;

        private detallerespuestatype detalle_RespuestaField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public detallerespuestatype Detalle_Respuesta
        {
            get
            {
                return this.detalle_RespuestaField;
            }
            set
            {
                this.detalle_RespuestaField = value;
                this.RaisePropertyChanged("Detalle_Respuesta");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class eliminaUbicacionProspectoFVRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "wsEliminaUbicacionProspectoFV-RQ", Namespace = "http://www.grr.net.fv/gis", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("wsEliminaUbicacionProspectoFV-RQ")]
        public Lite.ServiceEliminaProspecto.wsEliminaUbicacionProspectoFVRQType wsEliminaUbicacionProspectoFVRQ;

        public eliminaUbicacionProspectoFVRequest()
        {
        }

        public eliminaUbicacionProspectoFVRequest(Lite.ServiceEliminaProspecto.wsEliminaUbicacionProspectoFVRQType wsEliminaUbicacionProspectoFVRQ)
        {
            this.wsEliminaUbicacionProspectoFVRQ = wsEliminaUbicacionProspectoFVRQ;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class eliminaUbicacionProspectoFVResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "wsEliminaUbicacionProspectoFV-RS", Namespace = "http://www.grr.net.fv/gis", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("wsEliminaUbicacionProspectoFV-RS")]
        public Lite.ServiceEliminaProspecto.InfoProspecto wsEliminaUbicacionProspectoFVRS;

        public eliminaUbicacionProspectoFVResponse()
        {
        }

        public eliminaUbicacionProspectoFVResponse(Lite.ServiceEliminaProspecto.InfoProspecto wsEliminaUbicacionProspectoFVRS)
        {
            this.wsEliminaUbicacionProspectoFVRS = wsEliminaUbicacionProspectoFVRS;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WsEliminaUbicacionProspectoFVPortTypeChannel : Lite.ServiceEliminaProspecto.WsEliminaUbicacionProspectoFVPortType, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class eliminaUbicacionProspectoFVCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        public eliminaUbicacionProspectoFVCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        public Lite.ServiceEliminaProspecto.eliminaUbicacionProspectoFVResponse Result
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((Lite.ServiceEliminaProspecto.eliminaUbicacionProspectoFVResponse)(this.results[0]));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsEliminaUbicacionProspectoFVPortTypeClient : System.ServiceModel.ClientBase<Lite.ServiceEliminaProspecto.WsEliminaUbicacionProspectoFVPortType>, Lite.ServiceEliminaProspecto.WsEliminaUbicacionProspectoFVPortType
    {

        private BeginOperationDelegate onBegineliminaUbicacionProspectoFVDelegate;

        private EndOperationDelegate onEndeliminaUbicacionProspectoFVDelegate;

        private System.Threading.SendOrPostCallback oneliminaUbicacionProspectoFVCompletedDelegate;

        private BeginOperationDelegate onBeginOpenDelegate;

        private EndOperationDelegate onEndOpenDelegate;

        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;

        private BeginOperationDelegate onBeginCloseDelegate;

        private EndOperationDelegate onEndCloseDelegate;

        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;

        public WsEliminaUbicacionProspectoFVPortTypeClient()
        {
        }

        public WsEliminaUbicacionProspectoFVPortTypeClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public WsEliminaUbicacionProspectoFVPortTypeClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public WsEliminaUbicacionProspectoFVPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public WsEliminaUbicacionProspectoFVPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        public System.Net.CookieContainer CookieContainer
        {
            get
            {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null))
                {
                    return httpCookieContainerManager.CookieContainer;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null))
                {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else
                {
                    throw new System.InvalidOperationException("No se puede establecer el objeto CookieContainer. Asegúrese de que el enlace cont" +
                            "iene un objeto HttpCookieContainerBindingElement.");
                }
            }
        }

        public event System.EventHandler<eliminaUbicacionProspectoFVCompletedEventArgs> eliminaUbicacionProspectoFVCompleted;

        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;

        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Lite.ServiceEliminaProspecto.WsEliminaUbicacionProspectoFVPortType.BegineliminaUbicacionProspectoFV(Lite.ServiceEliminaProspecto.eliminaUbicacionProspectoFVRequest request, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BegineliminaUbicacionProspectoFV(request, callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lite.ServiceEliminaProspecto.eliminaUbicacionProspectoFVResponse Lite.ServiceEliminaProspecto.WsEliminaUbicacionProspectoFVPortType.EndeliminaUbicacionProspectoFV(System.IAsyncResult result)
        {
            return base.Channel.EndeliminaUbicacionProspectoFV(result);
        }

        private System.IAsyncResult OnBegineliminaUbicacionProspectoFV(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            Lite.ServiceEliminaProspecto.eliminaUbicacionProspectoFVRequest request = ((Lite.ServiceEliminaProspecto.eliminaUbicacionProspectoFVRequest)(inValues[0]));
            return ((Lite.ServiceEliminaProspecto.WsEliminaUbicacionProspectoFVPortType)(this)).BegineliminaUbicacionProspectoFV(request, callback, asyncState);
        }

        private object[] OnEndeliminaUbicacionProspectoFV(System.IAsyncResult result)
        {
            Lite.ServiceEliminaProspecto.eliminaUbicacionProspectoFVResponse retVal = ((Lite.ServiceEliminaProspecto.WsEliminaUbicacionProspectoFVPortType)(this)).EndeliminaUbicacionProspectoFV(result);
            return new object[] {
                    retVal};
        }

        private void OneliminaUbicacionProspectoFVCompleted(object state)
        {
            if ((this.eliminaUbicacionProspectoFVCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.eliminaUbicacionProspectoFVCompleted(this, new eliminaUbicacionProspectoFVCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        public void eliminaUbicacionProspectoFVAsync(Lite.ServiceEliminaProspecto.eliminaUbicacionProspectoFVRequest request)
        {
            this.eliminaUbicacionProspectoFVAsync(request, null);
        }

        public void eliminaUbicacionProspectoFVAsync(Lite.ServiceEliminaProspecto.eliminaUbicacionProspectoFVRequest request, object userState)
        {
            if ((this.onBegineliminaUbicacionProspectoFVDelegate == null))
            {
                this.onBegineliminaUbicacionProspectoFVDelegate = new BeginOperationDelegate(this.OnBegineliminaUbicacionProspectoFV);
            }
            if ((this.onEndeliminaUbicacionProspectoFVDelegate == null))
            {
                this.onEndeliminaUbicacionProspectoFVDelegate = new EndOperationDelegate(this.OnEndeliminaUbicacionProspectoFV);
            }
            if ((this.oneliminaUbicacionProspectoFVCompletedDelegate == null))
            {
                this.oneliminaUbicacionProspectoFVCompletedDelegate = new System.Threading.SendOrPostCallback(this.OneliminaUbicacionProspectoFVCompleted);
            }
            base.InvokeAsync(this.onBegineliminaUbicacionProspectoFVDelegate, new object[] {
                        request}, this.onEndeliminaUbicacionProspectoFVDelegate, this.oneliminaUbicacionProspectoFVCompletedDelegate, userState);
        }

        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }

        private object[] OnEndOpen(System.IAsyncResult result)
        {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }

        private void OnOpenCompleted(object state)
        {
            if ((this.OpenCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }

        public void OpenAsync()
        {
            this.OpenAsync(null);
        }

        public void OpenAsync(object userState)
        {
            if ((this.onBeginOpenDelegate == null))
            {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null))
            {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null))
            {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }

        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }

        private object[] OnEndClose(System.IAsyncResult result)
        {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }

        private void OnCloseCompleted(object state)
        {
            if ((this.CloseCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }

        public void CloseAsync()
        {
            this.CloseAsync(null);
        }

        public void CloseAsync(object userState)
        {
            if ((this.onBeginCloseDelegate == null))
            {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null))
            {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null))
            {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }

        protected override Lite.ServiceEliminaProspecto.WsEliminaUbicacionProspectoFVPortType CreateChannel()
        {
            return new WsEliminaUbicacionProspectoFVPortTypeClientChannel(this);
        }

        private class WsEliminaUbicacionProspectoFVPortTypeClientChannel : ChannelBase<Lite.ServiceEliminaProspecto.WsEliminaUbicacionProspectoFVPortType>, Lite.ServiceEliminaProspecto.WsEliminaUbicacionProspectoFVPortType
        {

            public WsEliminaUbicacionProspectoFVPortTypeClientChannel(System.ServiceModel.ClientBase<Lite.ServiceEliminaProspecto.WsEliminaUbicacionProspectoFVPortType> client) :
                base(client)
            {
            }

            public System.IAsyncResult BegineliminaUbicacionProspectoFV(Lite.ServiceEliminaProspecto.eliminaUbicacionProspectoFVRequest request, System.AsyncCallback callback, object asyncState)
            {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("eliminaUbicacionProspectoFV", _args, callback, asyncState);
                return _result;
            }

            public Lite.ServiceEliminaProspecto.eliminaUbicacionProspectoFVResponse EndeliminaUbicacionProspectoFV(System.IAsyncResult result)
            {
                object[] _args = new object[0];
                Lite.ServiceEliminaProspecto.eliminaUbicacionProspectoFVResponse _result = null;
                try
                {
                    _result = ((Lite.ServiceEliminaProspecto.eliminaUbicacionProspectoFVResponse)(base.EndInvoke("eliminaUbicacionProspectoFV", _args, result)));
                }
                catch { }
                return _result;
            }
        }
    }
}
