//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace Lite.ServiceGestionPuertos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.grr.net.fv/svc", ConfigurationName="ServiceGestionPuertos.WsGestionaInfoPuertosPortType")]
    public interface WsGestionaInfoPuertosPortType {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:actualizaPuertos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginactualizaPuertos(Lite.ServiceGestionPuertos.actualizaPuertosRequest request, System.AsyncCallback callback, object asyncState);
        
        Lite.ServiceGestionPuertos.actualizaPuertosResponse EndactualizaPuertos(System.IAsyncResult result);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="WsGestionaInfoPuertos-RQ-Type", Namespace="http://www.grr.net.fv/gis")]
    public partial class WsGestionaInfoPuertosRQType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string id_cajaField;
        
        private string nombreField;
        
        private string puertos_totalesField;
        
        private string puertos_ocupadosField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string id_caja {
            get {
                return this.id_cajaField;
            }
            set {
                this.id_cajaField = value;
                this.RaisePropertyChanged("id_caja");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string puertos_totales {
            get {
                return this.puertos_totalesField;
            }
            set {
                this.puertos_totalesField = value;
                this.RaisePropertyChanged("puertos_totales");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string puertos_ocupados {
            get {
                return this.puertos_ocupadosField;
            }
            set {
                this.puertos_ocupadosField = value;
                this.RaisePropertyChanged("puertos_ocupados");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.grr.net.fv/gis")]
    public partial class detallerespuestatype : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fechaRespuestaField;
        
        private string codigoRespuestaField;
        
        private string codigoErrorField;
        
        private string descripcionErrorField;
        
        private string mensajeErrorField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FechaRespuesta {
            get {
                return this.fechaRespuestaField;
            }
            set {
                this.fechaRespuestaField = value;
                this.RaisePropertyChanged("FechaRespuesta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CodigoRespuesta {
            get {
                return this.codigoRespuestaField;
            }
            set {
                this.codigoRespuestaField = value;
                this.RaisePropertyChanged("CodigoRespuesta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CodigoError {
            get {
                return this.codigoErrorField;
            }
            set {
                this.codigoErrorField = value;
                this.RaisePropertyChanged("CodigoError");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DescripcionError {
            get {
                return this.descripcionErrorField;
            }
            set {
                this.descripcionErrorField = value;
                this.RaisePropertyChanged("DescripcionError");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string MensajeError {
            get {
                return this.mensajeErrorField;
            }
            set {
                this.mensajeErrorField = value;
                this.RaisePropertyChanged("MensajeError");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.grr.net.fv/gis")]
    public partial class InfoPuertos : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string estadoField;
        
        private detallerespuestatype detalle_RespuestaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public detallerespuestatype Detalle_Respuesta {
            get {
                return this.detalle_RespuestaField;
            }
            set {
                this.detalle_RespuestaField = value;
                this.RaisePropertyChanged("Detalle_Respuesta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class actualizaPuertosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WsGestionaInfoPuertos-RQ", Namespace="http://www.grr.net.fv/gis", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("WsGestionaInfoPuertos-RQ")]
        public Lite.ServiceGestionPuertos.WsGestionaInfoPuertosRQType WsGestionaInfoPuertosRQ;
        
        public actualizaPuertosRequest() {
        }
        
        public actualizaPuertosRequest(Lite.ServiceGestionPuertos.WsGestionaInfoPuertosRQType WsGestionaInfoPuertosRQ) {
            this.WsGestionaInfoPuertosRQ = WsGestionaInfoPuertosRQ;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class actualizaPuertosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WsGestionaInfoPuertos-RS", Namespace="http://www.grr.net.fv/gis", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("WsGestionaInfoPuertos-RS")]
        public Lite.ServiceGestionPuertos.InfoPuertos WsGestionaInfoPuertosRS;
        
        public actualizaPuertosResponse() {
        }
        
        public actualizaPuertosResponse(Lite.ServiceGestionPuertos.InfoPuertos WsGestionaInfoPuertosRS) {
            this.WsGestionaInfoPuertosRS = WsGestionaInfoPuertosRS;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WsGestionaInfoPuertosPortTypeChannel : Lite.ServiceGestionPuertos.WsGestionaInfoPuertosPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class actualizaPuertosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public actualizaPuertosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Lite.ServiceGestionPuertos.actualizaPuertosResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Lite.ServiceGestionPuertos.actualizaPuertosResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsGestionaInfoPuertosPortTypeClient : System.ServiceModel.ClientBase<Lite.ServiceGestionPuertos.WsGestionaInfoPuertosPortType>, Lite.ServiceGestionPuertos.WsGestionaInfoPuertosPortType {
        
        private BeginOperationDelegate onBeginactualizaPuertosDelegate;
        
        private EndOperationDelegate onEndactualizaPuertosDelegate;
        
        private System.Threading.SendOrPostCallback onactualizaPuertosCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public WsGestionaInfoPuertosPortTypeClient() {
        }
        
        public WsGestionaInfoPuertosPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsGestionaInfoPuertosPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsGestionaInfoPuertosPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsGestionaInfoPuertosPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("No se puede establecer el objeto CookieContainer. Asegúrese de que el enlace cont" +
                            "iene un objeto HttpCookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<actualizaPuertosCompletedEventArgs> actualizaPuertosCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Lite.ServiceGestionPuertos.WsGestionaInfoPuertosPortType.BeginactualizaPuertos(Lite.ServiceGestionPuertos.actualizaPuertosRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginactualizaPuertos(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lite.ServiceGestionPuertos.actualizaPuertosResponse Lite.ServiceGestionPuertos.WsGestionaInfoPuertosPortType.EndactualizaPuertos(System.IAsyncResult result) {
            return base.Channel.EndactualizaPuertos(result);
        }
        
        private System.IAsyncResult OnBeginactualizaPuertos(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Lite.ServiceGestionPuertos.actualizaPuertosRequest request = ((Lite.ServiceGestionPuertos.actualizaPuertosRequest)(inValues[0]));
            return ((Lite.ServiceGestionPuertos.WsGestionaInfoPuertosPortType)(this)).BeginactualizaPuertos(request, callback, asyncState);
        }
        
        private object[] OnEndactualizaPuertos(System.IAsyncResult result) {
            Lite.ServiceGestionPuertos.actualizaPuertosResponse retVal = ((Lite.ServiceGestionPuertos.WsGestionaInfoPuertosPortType)(this)).EndactualizaPuertos(result);
            return new object[] {
                    retVal};
        }
        
        private void OnactualizaPuertosCompleted(object state) {
            if ((this.actualizaPuertosCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.actualizaPuertosCompleted(this, new actualizaPuertosCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void actualizaPuertosAsync(Lite.ServiceGestionPuertos.actualizaPuertosRequest request) {
            this.actualizaPuertosAsync(request, null);
        }
        
        public void actualizaPuertosAsync(Lite.ServiceGestionPuertos.actualizaPuertosRequest request, object userState) {
            if ((this.onBeginactualizaPuertosDelegate == null)) {
                this.onBeginactualizaPuertosDelegate = new BeginOperationDelegate(this.OnBeginactualizaPuertos);
            }
            if ((this.onEndactualizaPuertosDelegate == null)) {
                this.onEndactualizaPuertosDelegate = new EndOperationDelegate(this.OnEndactualizaPuertos);
            }
            if ((this.onactualizaPuertosCompletedDelegate == null)) {
                this.onactualizaPuertosCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnactualizaPuertosCompleted);
            }
            base.InvokeAsync(this.onBeginactualizaPuertosDelegate, new object[] {
                        request}, this.onEndactualizaPuertosDelegate, this.onactualizaPuertosCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Lite.ServiceGestionPuertos.WsGestionaInfoPuertosPortType CreateChannel() {
            return new WsGestionaInfoPuertosPortTypeClientChannel(this);
        }
        
        private class WsGestionaInfoPuertosPortTypeClientChannel : ChannelBase<Lite.ServiceGestionPuertos.WsGestionaInfoPuertosPortType>, Lite.ServiceGestionPuertos.WsGestionaInfoPuertosPortType {
            
            public WsGestionaInfoPuertosPortTypeClientChannel(System.ServiceModel.ClientBase<Lite.ServiceGestionPuertos.WsGestionaInfoPuertosPortType> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginactualizaPuertos(Lite.ServiceGestionPuertos.actualizaPuertosRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("actualizaPuertos", _args, callback, asyncState);
                return _result;
            }
            
            public Lite.ServiceGestionPuertos.actualizaPuertosResponse EndactualizaPuertos(System.IAsyncResult result) {
                object[] _args = new object[0];
                Lite.ServiceGestionPuertos.actualizaPuertosResponse _result = ((Lite.ServiceGestionPuertos.actualizaPuertosResponse)(base.EndInvoke("actualizaPuertos", _args, result)));
                return _result;
            }
        }
    }
}
