//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18063
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace Lite.ServiceAlmacenaProspecto {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.grr.net.fv/svc", ConfigurationName="ServiceAlmacenaProspecto.WsAlmacenaUbicacionProspectoFVPortType")]
    public interface WsAlmacenaUbicacionProspectoFVPortType {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:almacenaUbicacionProspectoFV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginalmacenaUbicacionProspectoFV(Lite.ServiceAlmacenaProspecto.almacenaUbicacionProspectoFVRequest request, System.AsyncCallback callback, object asyncState);
        
        Lite.ServiceAlmacenaProspecto.almacenaUbicacionProspectoFVResponse EndalmacenaUbicacionProspectoFV(System.IAsyncResult result);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="wsAlmacenaUbicacionProspectoFV-RQ-Type", Namespace="http://www.grr.net.fv/gis")]
    public partial class wsAlmacenaUbicacionProspectoFVRQType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nombreField;
        
        private string direccionField;
        
        private string telefonoField;
        
        private string tipoField;
        
        private string paqueteField;
        
        private string fechaField;
        
        private string longitudField;
        
        private string latitudField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string paquete {
            get {
                return this.paqueteField;
            }
            set {
                this.paqueteField = value;
                this.RaisePropertyChanged("paquete");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string longitud {
            get {
                return this.longitudField;
            }
            set {
                this.longitudField = value;
                this.RaisePropertyChanged("longitud");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string latitud {
            get {
                return this.latitudField;
            }
            set {
                this.latitudField = value;
                this.RaisePropertyChanged("latitud");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.grr.net.fv/gis")]
    public partial class detallerespuestatype : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fechaRespuestaField;
        
        private string codigoRespuestaField;
        
        private string codigoErrorField;
        
        private string descripcionErrorField;
        
        private string mensajeErrorField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FechaRespuesta {
            get {
                return this.fechaRespuestaField;
            }
            set {
                this.fechaRespuestaField = value;
                this.RaisePropertyChanged("FechaRespuesta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CodigoRespuesta {
            get {
                return this.codigoRespuestaField;
            }
            set {
                this.codigoRespuestaField = value;
                this.RaisePropertyChanged("CodigoRespuesta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CodigoError {
            get {
                return this.codigoErrorField;
            }
            set {
                this.codigoErrorField = value;
                this.RaisePropertyChanged("CodigoError");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DescripcionError {
            get {
                return this.descripcionErrorField;
            }
            set {
                this.descripcionErrorField = value;
                this.RaisePropertyChanged("DescripcionError");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string MensajeError {
            get {
                return this.mensajeErrorField;
            }
            set {
                this.mensajeErrorField = value;
                this.RaisePropertyChanged("MensajeError");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.grr.net.fv/gis")]
    public partial class InfoProspecto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idSwField;
        
        private string estadoField;
        
        private detallerespuestatype detalle_RespuestaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string idSw {
            get {
                return this.idSwField;
            }
            set {
                this.idSwField = value;
                this.RaisePropertyChanged("idSw");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public detallerespuestatype Detalle_Respuesta {
            get {
                return this.detalle_RespuestaField;
            }
            set {
                this.detalle_RespuestaField = value;
                this.RaisePropertyChanged("Detalle_Respuesta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class almacenaUbicacionProspectoFVRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wsAlmacenaUbicacionProspectoFV-RQ", Namespace="http://www.grr.net.fv/gis", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("wsAlmacenaUbicacionProspectoFV-RQ")]
        public Lite.ServiceAlmacenaProspecto.wsAlmacenaUbicacionProspectoFVRQType wsAlmacenaUbicacionProspectoFVRQ;
        
        public almacenaUbicacionProspectoFVRequest() {
        }
        
        public almacenaUbicacionProspectoFVRequest(Lite.ServiceAlmacenaProspecto.wsAlmacenaUbicacionProspectoFVRQType wsAlmacenaUbicacionProspectoFVRQ) {
            this.wsAlmacenaUbicacionProspectoFVRQ = wsAlmacenaUbicacionProspectoFVRQ;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class almacenaUbicacionProspectoFVResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wsAlmacenaUbicacionProspectoFV-RS", Namespace="http://www.grr.net.fv/gis", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("wsAlmacenaUbicacionProspectoFV-RS")]
        public Lite.ServiceAlmacenaProspecto.InfoProspecto wsAlmacenaUbicacionProspectoFVRS;
        
        public almacenaUbicacionProspectoFVResponse() {
        }
        
        public almacenaUbicacionProspectoFVResponse(Lite.ServiceAlmacenaProspecto.InfoProspecto wsAlmacenaUbicacionProspectoFVRS) {
            this.wsAlmacenaUbicacionProspectoFVRS = wsAlmacenaUbicacionProspectoFVRS;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WsAlmacenaUbicacionProspectoFVPortTypeChannel : Lite.ServiceAlmacenaProspecto.WsAlmacenaUbicacionProspectoFVPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class almacenaUbicacionProspectoFVCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public almacenaUbicacionProspectoFVCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Lite.ServiceAlmacenaProspecto.almacenaUbicacionProspectoFVResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Lite.ServiceAlmacenaProspecto.almacenaUbicacionProspectoFVResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsAlmacenaUbicacionProspectoFVPortTypeClient : System.ServiceModel.ClientBase<Lite.ServiceAlmacenaProspecto.WsAlmacenaUbicacionProspectoFVPortType>, Lite.ServiceAlmacenaProspecto.WsAlmacenaUbicacionProspectoFVPortType {
        
        private BeginOperationDelegate onBeginalmacenaUbicacionProspectoFVDelegate;
        
        private EndOperationDelegate onEndalmacenaUbicacionProspectoFVDelegate;
        
        private System.Threading.SendOrPostCallback onalmacenaUbicacionProspectoFVCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public WsAlmacenaUbicacionProspectoFVPortTypeClient() {
        }
        
        public WsAlmacenaUbicacionProspectoFVPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsAlmacenaUbicacionProspectoFVPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsAlmacenaUbicacionProspectoFVPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsAlmacenaUbicacionProspectoFVPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("No se puede establecer el objeto CookieContainer. Asegúrese de que el enlace cont" +
                            "iene un objeto HttpCookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<almacenaUbicacionProspectoFVCompletedEventArgs> almacenaUbicacionProspectoFVCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Lite.ServiceAlmacenaProspecto.WsAlmacenaUbicacionProspectoFVPortType.BeginalmacenaUbicacionProspectoFV(Lite.ServiceAlmacenaProspecto.almacenaUbicacionProspectoFVRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginalmacenaUbicacionProspectoFV(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lite.ServiceAlmacenaProspecto.almacenaUbicacionProspectoFVResponse Lite.ServiceAlmacenaProspecto.WsAlmacenaUbicacionProspectoFVPortType.EndalmacenaUbicacionProspectoFV(System.IAsyncResult result) {
            return base.Channel.EndalmacenaUbicacionProspectoFV(result);
        }
        
        private System.IAsyncResult OnBeginalmacenaUbicacionProspectoFV(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Lite.ServiceAlmacenaProspecto.almacenaUbicacionProspectoFVRequest request = ((Lite.ServiceAlmacenaProspecto.almacenaUbicacionProspectoFVRequest)(inValues[0]));
            return ((Lite.ServiceAlmacenaProspecto.WsAlmacenaUbicacionProspectoFVPortType)(this)).BeginalmacenaUbicacionProspectoFV(request, callback, asyncState);
        }
        
        private object[] OnEndalmacenaUbicacionProspectoFV(System.IAsyncResult result) {
            Lite.ServiceAlmacenaProspecto.almacenaUbicacionProspectoFVResponse retVal = ((Lite.ServiceAlmacenaProspecto.WsAlmacenaUbicacionProspectoFVPortType)(this)).EndalmacenaUbicacionProspectoFV(result);
            return new object[] {
                    retVal};
        }
        
        private void OnalmacenaUbicacionProspectoFVCompleted(object state) {
            if ((this.almacenaUbicacionProspectoFVCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.almacenaUbicacionProspectoFVCompleted(this, new almacenaUbicacionProspectoFVCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void almacenaUbicacionProspectoFVAsync(Lite.ServiceAlmacenaProspecto.almacenaUbicacionProspectoFVRequest request) {
            this.almacenaUbicacionProspectoFVAsync(request, null);
        }
        
        public void almacenaUbicacionProspectoFVAsync(Lite.ServiceAlmacenaProspecto.almacenaUbicacionProspectoFVRequest request, object userState) {
            if ((this.onBeginalmacenaUbicacionProspectoFVDelegate == null)) {
                this.onBeginalmacenaUbicacionProspectoFVDelegate = new BeginOperationDelegate(this.OnBeginalmacenaUbicacionProspectoFV);
            }
            if ((this.onEndalmacenaUbicacionProspectoFVDelegate == null)) {
                this.onEndalmacenaUbicacionProspectoFVDelegate = new EndOperationDelegate(this.OnEndalmacenaUbicacionProspectoFV);
            }
            if ((this.onalmacenaUbicacionProspectoFVCompletedDelegate == null)) {
                this.onalmacenaUbicacionProspectoFVCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnalmacenaUbicacionProspectoFVCompleted);
            }
            base.InvokeAsync(this.onBeginalmacenaUbicacionProspectoFVDelegate, new object[] {
                        request}, this.onEndalmacenaUbicacionProspectoFVDelegate, this.onalmacenaUbicacionProspectoFVCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Lite.ServiceAlmacenaProspecto.WsAlmacenaUbicacionProspectoFVPortType CreateChannel() {
            return new WsAlmacenaUbicacionProspectoFVPortTypeClientChannel(this);
        }
        
        private class WsAlmacenaUbicacionProspectoFVPortTypeClientChannel : ChannelBase<Lite.ServiceAlmacenaProspecto.WsAlmacenaUbicacionProspectoFVPortType>, Lite.ServiceAlmacenaProspecto.WsAlmacenaUbicacionProspectoFVPortType {
            
            public WsAlmacenaUbicacionProspectoFVPortTypeClientChannel(System.ServiceModel.ClientBase<Lite.ServiceAlmacenaProspecto.WsAlmacenaUbicacionProspectoFVPortType> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginalmacenaUbicacionProspectoFV(Lite.ServiceAlmacenaProspecto.almacenaUbicacionProspectoFVRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("almacenaUbicacionProspectoFV", _args, callback, asyncState);
                return _result;
            }
            
            public Lite.ServiceAlmacenaProspecto.almacenaUbicacionProspectoFVResponse EndalmacenaUbicacionProspectoFV(System.IAsyncResult result) {
                object[] _args = new object[0];
                Lite.ServiceAlmacenaProspecto.almacenaUbicacionProspectoFVResponse _result = null;
                try
                {
                    _result = ((Lite.ServiceAlmacenaProspecto.almacenaUbicacionProspectoFVResponse)(base.EndInvoke("almacenaUbicacionProspectoFV", _args, result)));
                }
                catch { }
                return _result;
            }
        }
    }
}
