//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace Lite.ServiceAlmacenaIncidente {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.grr.net.fv/svc", ConfigurationName="ServiceAlmacenaIncidente.WsAlmacenaUbicacionIncidentePortType")]
    public interface WsAlmacenaUbicacionIncidentePortType {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:almacenaUbicacionIncidente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginalmacenaUbicacionIncidente(Lite.ServiceAlmacenaIncidente.almacenaUbicacionIncidenteRequest request, System.AsyncCallback callback, object asyncState);
        
        Lite.ServiceAlmacenaIncidente.almacenaUbicacionIncidenteResponse EndalmacenaUbicacionIncidente(System.IAsyncResult result);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="wsAlmacenaUbicacionIncidente-RQ-Type", Namespace="http://www.grr.net.fv/gis")]
    public partial class wsAlmacenaUbicacionIncidenteRQType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nombreField;
        
        private string folioField;
        
        private string longitudField;
        
        private string latitudField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string folio {
            get {
                return this.folioField;
            }
            set {
                this.folioField = value;
                this.RaisePropertyChanged("folio");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string longitud {
            get {
                return this.longitudField;
            }
            set {
                this.longitudField = value;
                this.RaisePropertyChanged("longitud");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string latitud {
            get {
                return this.latitudField;
            }
            set {
                this.latitudField = value;
                this.RaisePropertyChanged("latitud");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.grr.net.fv/gis")]
    public partial class detallerespuestatype : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fechaRespuestaField;
        
        private string codigoRespuestaField;
        
        private string codigoErrorField;
        
        private string descripcionErrorField;
        
        private string mensajeErrorField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FechaRespuesta {
            get {
                return this.fechaRespuestaField;
            }
            set {
                this.fechaRespuestaField = value;
                this.RaisePropertyChanged("FechaRespuesta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CodigoRespuesta {
            get {
                return this.codigoRespuestaField;
            }
            set {
                this.codigoRespuestaField = value;
                this.RaisePropertyChanged("CodigoRespuesta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CodigoError {
            get {
                return this.codigoErrorField;
            }
            set {
                this.codigoErrorField = value;
                this.RaisePropertyChanged("CodigoError");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DescripcionError {
            get {
                return this.descripcionErrorField;
            }
            set {
                this.descripcionErrorField = value;
                this.RaisePropertyChanged("DescripcionError");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string MensajeError {
            get {
                return this.mensajeErrorField;
            }
            set {
                this.mensajeErrorField = value;
                this.RaisePropertyChanged("MensajeError");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.grr.net.fv/gis")]
    public partial class InfoIncidente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idSwField;
        
        private string estadoField;
        
        private detallerespuestatype detalle_RespuestaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string idSw {
            get {
                return this.idSwField;
            }
            set {
                this.idSwField = value;
                this.RaisePropertyChanged("idSw");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public detallerespuestatype Detalle_Respuesta {
            get {
                return this.detalle_RespuestaField;
            }
            set {
                this.detalle_RespuestaField = value;
                this.RaisePropertyChanged("Detalle_Respuesta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class almacenaUbicacionIncidenteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wsAlmacenaUbicacionIncidente-RQ", Namespace="http://www.grr.net.fv/gis", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("wsAlmacenaUbicacionIncidente-RQ")]
        public Lite.ServiceAlmacenaIncidente.wsAlmacenaUbicacionIncidenteRQType wsAlmacenaUbicacionIncidenteRQ;
        
        public almacenaUbicacionIncidenteRequest() {
        }
        
        public almacenaUbicacionIncidenteRequest(Lite.ServiceAlmacenaIncidente.wsAlmacenaUbicacionIncidenteRQType wsAlmacenaUbicacionIncidenteRQ) {
            this.wsAlmacenaUbicacionIncidenteRQ = wsAlmacenaUbicacionIncidenteRQ;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class almacenaUbicacionIncidenteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wsAlmacenaUbicacionIncidente-RS", Namespace="http://www.grr.net.fv/gis", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("wsAlmacenaUbicacionIncidente-RS")]
        public Lite.ServiceAlmacenaIncidente.InfoIncidente wsAlmacenaUbicacionIncidenteRS;
        
        public almacenaUbicacionIncidenteResponse() {
        }
        
        public almacenaUbicacionIncidenteResponse(Lite.ServiceAlmacenaIncidente.InfoIncidente wsAlmacenaUbicacionIncidenteRS) {
            this.wsAlmacenaUbicacionIncidenteRS = wsAlmacenaUbicacionIncidenteRS;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WsAlmacenaUbicacionIncidentePortTypeChannel : Lite.ServiceAlmacenaIncidente.WsAlmacenaUbicacionIncidentePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class almacenaUbicacionIncidenteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public almacenaUbicacionIncidenteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Lite.ServiceAlmacenaIncidente.almacenaUbicacionIncidenteResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Lite.ServiceAlmacenaIncidente.almacenaUbicacionIncidenteResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsAlmacenaUbicacionIncidentePortTypeClient : System.ServiceModel.ClientBase<Lite.ServiceAlmacenaIncidente.WsAlmacenaUbicacionIncidentePortType>, Lite.ServiceAlmacenaIncidente.WsAlmacenaUbicacionIncidentePortType {
        
        private BeginOperationDelegate onBeginalmacenaUbicacionIncidenteDelegate;
        
        private EndOperationDelegate onEndalmacenaUbicacionIncidenteDelegate;
        
        private System.Threading.SendOrPostCallback onalmacenaUbicacionIncidenteCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public WsAlmacenaUbicacionIncidentePortTypeClient() {
        }
        
        public WsAlmacenaUbicacionIncidentePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsAlmacenaUbicacionIncidentePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsAlmacenaUbicacionIncidentePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsAlmacenaUbicacionIncidentePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("No se puede establecer el objeto CookieContainer. Asegúrese de que el enlace cont" +
                            "iene un objeto HttpCookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<almacenaUbicacionIncidenteCompletedEventArgs> almacenaUbicacionIncidenteCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Lite.ServiceAlmacenaIncidente.WsAlmacenaUbicacionIncidentePortType.BeginalmacenaUbicacionIncidente(Lite.ServiceAlmacenaIncidente.almacenaUbicacionIncidenteRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginalmacenaUbicacionIncidente(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lite.ServiceAlmacenaIncidente.almacenaUbicacionIncidenteResponse Lite.ServiceAlmacenaIncidente.WsAlmacenaUbicacionIncidentePortType.EndalmacenaUbicacionIncidente(System.IAsyncResult result) {
            return base.Channel.EndalmacenaUbicacionIncidente(result);
        }
        
        private System.IAsyncResult OnBeginalmacenaUbicacionIncidente(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Lite.ServiceAlmacenaIncidente.almacenaUbicacionIncidenteRequest request = ((Lite.ServiceAlmacenaIncidente.almacenaUbicacionIncidenteRequest)(inValues[0]));
            return ((Lite.ServiceAlmacenaIncidente.WsAlmacenaUbicacionIncidentePortType)(this)).BeginalmacenaUbicacionIncidente(request, callback, asyncState);
        }
        
        private object[] OnEndalmacenaUbicacionIncidente(System.IAsyncResult result) {
            Lite.ServiceAlmacenaIncidente.almacenaUbicacionIncidenteResponse retVal = ((Lite.ServiceAlmacenaIncidente.WsAlmacenaUbicacionIncidentePortType)(this)).EndalmacenaUbicacionIncidente(result);
            return new object[] {
                    retVal};
        }
        
        private void OnalmacenaUbicacionIncidenteCompleted(object state) {
            if ((this.almacenaUbicacionIncidenteCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.almacenaUbicacionIncidenteCompleted(this, new almacenaUbicacionIncidenteCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void almacenaUbicacionIncidenteAsync(Lite.ServiceAlmacenaIncidente.almacenaUbicacionIncidenteRequest request) {
            this.almacenaUbicacionIncidenteAsync(request, null);
        }
        
        public void almacenaUbicacionIncidenteAsync(Lite.ServiceAlmacenaIncidente.almacenaUbicacionIncidenteRequest request, object userState) {
            if ((this.onBeginalmacenaUbicacionIncidenteDelegate == null)) {
                this.onBeginalmacenaUbicacionIncidenteDelegate = new BeginOperationDelegate(this.OnBeginalmacenaUbicacionIncidente);
            }
            if ((this.onEndalmacenaUbicacionIncidenteDelegate == null)) {
                this.onEndalmacenaUbicacionIncidenteDelegate = new EndOperationDelegate(this.OnEndalmacenaUbicacionIncidente);
            }
            if ((this.onalmacenaUbicacionIncidenteCompletedDelegate == null)) {
                this.onalmacenaUbicacionIncidenteCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnalmacenaUbicacionIncidenteCompleted);
            }
            base.InvokeAsync(this.onBeginalmacenaUbicacionIncidenteDelegate, new object[] {
                        request}, this.onEndalmacenaUbicacionIncidenteDelegate, this.onalmacenaUbicacionIncidenteCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Lite.ServiceAlmacenaIncidente.WsAlmacenaUbicacionIncidentePortType CreateChannel() {
            return new WsAlmacenaUbicacionIncidentePortTypeClientChannel(this);
        }
        
        private class WsAlmacenaUbicacionIncidentePortTypeClientChannel : ChannelBase<Lite.ServiceAlmacenaIncidente.WsAlmacenaUbicacionIncidentePortType>, Lite.ServiceAlmacenaIncidente.WsAlmacenaUbicacionIncidentePortType {
            
            public WsAlmacenaUbicacionIncidentePortTypeClientChannel(System.ServiceModel.ClientBase<Lite.ServiceAlmacenaIncidente.WsAlmacenaUbicacionIncidentePortType> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginalmacenaUbicacionIncidente(Lite.ServiceAlmacenaIncidente.almacenaUbicacionIncidenteRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("almacenaUbicacionIncidente", _args, callback, asyncState);
                return _result;
            }
            
            public Lite.ServiceAlmacenaIncidente.almacenaUbicacionIncidenteResponse EndalmacenaUbicacionIncidente(System.IAsyncResult result) {
                object[] _args = new object[0];
                Lite.ServiceAlmacenaIncidente.almacenaUbicacionIncidenteResponse _result = ((Lite.ServiceAlmacenaIncidente.almacenaUbicacionIncidenteResponse)(base.EndInvoke("almacenaUbicacionIncidente", _args, result)));
                return _result;
            }
        }
    }
}
