//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace Lite.ServiceFactibilidadEmpresarial {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.grr.net.fv/svc", ConfigurationName="ServiceFactibilidadEmpresarial.WsFactibilidadEmpresarialPortType")]
    public interface WsFactibilidadEmpresarialPortType {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:getFactibilidadEmpresarial", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BegingetFactibilidadEmpresarial(Lite.ServiceFactibilidadEmpresarial.getFactibilidadEmpresarialRequest request, System.AsyncCallback callback, object asyncState);
        
        Lite.ServiceFactibilidadEmpresarial.getFactibilidadEmpresarialResponse EndgetFactibilidadEmpresarial(System.IAsyncResult result);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="wsFactibilidadEmpresarial-RQ-Type", Namespace="http://www.grr.net.fv/gis")]
    public partial class wsFactibilidadEmpresarialRQType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string latitudField;
        
        private string longitudField;
        
        private string coloniaField;
        
        private string cpField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string latitud {
            get {
                return this.latitudField;
            }
            set {
                this.latitudField = value;
                this.RaisePropertyChanged("latitud");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string longitud {
            get {
                return this.longitudField;
            }
            set {
                this.longitudField = value;
                this.RaisePropertyChanged("longitud");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string colonia {
            get {
                return this.coloniaField;
            }
            set {
                this.coloniaField = value;
                this.RaisePropertyChanged("colonia");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string cp {
            get {
                return this.cpField;
            }
            set {
                this.cpField = value;
                this.RaisePropertyChanged("cp");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.grr.net.fv/gis")]
    public partial class detalleRespuestaType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mensajeTransaccionField;
        
        private string codigoErrorField;
        
        private string descripcionErrorField;
        
        private string mensajeErrorField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MensajeTransaccion {
            get {
                return this.mensajeTransaccionField;
            }
            set {
                this.mensajeTransaccionField = value;
                this.RaisePropertyChanged("MensajeTransaccion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CodigoError {
            get {
                return this.codigoErrorField;
            }
            set {
                this.codigoErrorField = value;
                this.RaisePropertyChanged("CodigoError");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DescripcionError {
            get {
                return this.descripcionErrorField;
            }
            set {
                this.descripcionErrorField = value;
                this.RaisePropertyChanged("DescripcionError");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MensajeError {
            get {
                return this.mensajeErrorField;
            }
            set {
                this.mensajeErrorField = value;
                this.RaisePropertyChanged("MensajeError");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="wsFactibilidadEmpresarial-RS-Type", Namespace="http://www.grr.net.fv/gis")]
    public partial class wsFactibilidadEmpresarialRSType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string factibilidadField;
        
        private string comentarioField;
        
        private string domicilioField;
        
        private string cluster_totalplayField;
        
        private string region_enlaceField;
        
        private string ciudad_enlaceField;
        
        private string distrito_enlaceField;
        
        private string buffer_enlaceField;
        
        private detalleRespuestaType detalleRespuestaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string factibilidad {
            get {
                return this.factibilidadField;
            }
            set {
                this.factibilidadField = value;
                this.RaisePropertyChanged("factibilidad");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string comentario {
            get {
                return this.comentarioField;
            }
            set {
                this.comentarioField = value;
                this.RaisePropertyChanged("comentario");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string domicilio {
            get {
                return this.domicilioField;
            }
            set {
                this.domicilioField = value;
                this.RaisePropertyChanged("domicilio");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string cluster_totalplay {
            get {
                return this.cluster_totalplayField;
            }
            set {
                this.cluster_totalplayField = value;
                this.RaisePropertyChanged("cluster_totalplay");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string region_enlace {
            get {
                return this.region_enlaceField;
            }
            set {
                this.region_enlaceField = value;
                this.RaisePropertyChanged("region_enlace");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ciudad_enlace {
            get {
                return this.ciudad_enlaceField;
            }
            set {
                this.ciudad_enlaceField = value;
                this.RaisePropertyChanged("ciudad_enlace");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string distrito_enlace {
            get {
                return this.distrito_enlaceField;
            }
            set {
                this.distrito_enlaceField = value;
                this.RaisePropertyChanged("distrito_enlace");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string buffer_enlace {
            get {
                return this.buffer_enlaceField;
            }
            set {
                this.buffer_enlaceField = value;
                this.RaisePropertyChanged("buffer_enlace");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public detalleRespuestaType detalleRespuesta {
            get {
                return this.detalleRespuestaField;
            }
            set {
                this.detalleRespuestaField = value;
                this.RaisePropertyChanged("detalleRespuesta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFactibilidadEmpresarialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wsFactibilidadEmpresarial-RQ", Namespace="http://www.grr.net.fv/gis", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("wsFactibilidadEmpresarial-RQ")]
        public Lite.ServiceFactibilidadEmpresarial.wsFactibilidadEmpresarialRQType wsFactibilidadEmpresarialRQ;
        
        public getFactibilidadEmpresarialRequest() {
        }
        
        public getFactibilidadEmpresarialRequest(Lite.ServiceFactibilidadEmpresarial.wsFactibilidadEmpresarialRQType wsFactibilidadEmpresarialRQ) {
            this.wsFactibilidadEmpresarialRQ = wsFactibilidadEmpresarialRQ;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFactibilidadEmpresarialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wsFactibilidadEmpresarial-RS", Namespace="http://www.grr.net.fv/gis", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("wsFactibilidadEmpresarial-RS")]
        public Lite.ServiceFactibilidadEmpresarial.wsFactibilidadEmpresarialRSType wsFactibilidadEmpresarialRS;
        
        public getFactibilidadEmpresarialResponse() {
        }
        
        public getFactibilidadEmpresarialResponse(Lite.ServiceFactibilidadEmpresarial.wsFactibilidadEmpresarialRSType wsFactibilidadEmpresarialRS) {
            this.wsFactibilidadEmpresarialRS = wsFactibilidadEmpresarialRS;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WsFactibilidadEmpresarialPortTypeChannel : Lite.ServiceFactibilidadEmpresarial.WsFactibilidadEmpresarialPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getFactibilidadEmpresarialCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getFactibilidadEmpresarialCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Lite.ServiceFactibilidadEmpresarial.wsFactibilidadEmpresarialRSType Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Lite.ServiceFactibilidadEmpresarial.wsFactibilidadEmpresarialRSType)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsFactibilidadEmpresarialPortTypeClient : System.ServiceModel.ClientBase<Lite.ServiceFactibilidadEmpresarial.WsFactibilidadEmpresarialPortType>, Lite.ServiceFactibilidadEmpresarial.WsFactibilidadEmpresarialPortType {
        
        private BeginOperationDelegate onBegingetFactibilidadEmpresarialDelegate;
        
        private EndOperationDelegate onEndgetFactibilidadEmpresarialDelegate;
        
        private System.Threading.SendOrPostCallback ongetFactibilidadEmpresarialCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public WsFactibilidadEmpresarialPortTypeClient() {
        }
        
        public WsFactibilidadEmpresarialPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsFactibilidadEmpresarialPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsFactibilidadEmpresarialPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsFactibilidadEmpresarialPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("No se puede establecer el objeto CookieContainer. Asegúrese de que el enlace cont" +
                            "iene un objeto HttpCookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<getFactibilidadEmpresarialCompletedEventArgs> getFactibilidadEmpresarialCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Lite.ServiceFactibilidadEmpresarial.WsFactibilidadEmpresarialPortType.BegingetFactibilidadEmpresarial(Lite.ServiceFactibilidadEmpresarial.getFactibilidadEmpresarialRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetFactibilidadEmpresarial(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BegingetFactibilidadEmpresarial(Lite.ServiceFactibilidadEmpresarial.wsFactibilidadEmpresarialRQType wsFactibilidadEmpresarialRQ, System.AsyncCallback callback, object asyncState) {
            Lite.ServiceFactibilidadEmpresarial.getFactibilidadEmpresarialRequest inValue = new Lite.ServiceFactibilidadEmpresarial.getFactibilidadEmpresarialRequest();
            inValue.wsFactibilidadEmpresarialRQ = wsFactibilidadEmpresarialRQ;
            return ((Lite.ServiceFactibilidadEmpresarial.WsFactibilidadEmpresarialPortType)(this)).BegingetFactibilidadEmpresarial(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lite.ServiceFactibilidadEmpresarial.getFactibilidadEmpresarialResponse Lite.ServiceFactibilidadEmpresarial.WsFactibilidadEmpresarialPortType.EndgetFactibilidadEmpresarial(System.IAsyncResult result) {
            return base.Channel.EndgetFactibilidadEmpresarial(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private Lite.ServiceFactibilidadEmpresarial.wsFactibilidadEmpresarialRSType EndgetFactibilidadEmpresarial(System.IAsyncResult result) {
            Lite.ServiceFactibilidadEmpresarial.getFactibilidadEmpresarialResponse retVal = ((Lite.ServiceFactibilidadEmpresarial.WsFactibilidadEmpresarialPortType)(this)).EndgetFactibilidadEmpresarial(result);
            return retVal.wsFactibilidadEmpresarialRS;
        }
        
        private System.IAsyncResult OnBegingetFactibilidadEmpresarial(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Lite.ServiceFactibilidadEmpresarial.wsFactibilidadEmpresarialRQType wsFactibilidadEmpresarialRQ = ((Lite.ServiceFactibilidadEmpresarial.wsFactibilidadEmpresarialRQType)(inValues[0]));
            return this.BegingetFactibilidadEmpresarial(wsFactibilidadEmpresarialRQ, callback, asyncState);
        }
        
        private object[] OnEndgetFactibilidadEmpresarial(System.IAsyncResult result) {
            Lite.ServiceFactibilidadEmpresarial.wsFactibilidadEmpresarialRSType retVal = this.EndgetFactibilidadEmpresarial(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetFactibilidadEmpresarialCompleted(object state) {
            if ((this.getFactibilidadEmpresarialCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getFactibilidadEmpresarialCompleted(this, new getFactibilidadEmpresarialCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getFactibilidadEmpresarialAsync(Lite.ServiceFactibilidadEmpresarial.wsFactibilidadEmpresarialRQType wsFactibilidadEmpresarialRQ) {
            this.getFactibilidadEmpresarialAsync(wsFactibilidadEmpresarialRQ, null);
        }
        
        public void getFactibilidadEmpresarialAsync(Lite.ServiceFactibilidadEmpresarial.wsFactibilidadEmpresarialRQType wsFactibilidadEmpresarialRQ, object userState) {
            if ((this.onBegingetFactibilidadEmpresarialDelegate == null)) {
                this.onBegingetFactibilidadEmpresarialDelegate = new BeginOperationDelegate(this.OnBegingetFactibilidadEmpresarial);
            }
            if ((this.onEndgetFactibilidadEmpresarialDelegate == null)) {
                this.onEndgetFactibilidadEmpresarialDelegate = new EndOperationDelegate(this.OnEndgetFactibilidadEmpresarial);
            }
            if ((this.ongetFactibilidadEmpresarialCompletedDelegate == null)) {
                this.ongetFactibilidadEmpresarialCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetFactibilidadEmpresarialCompleted);
            }
            base.InvokeAsync(this.onBegingetFactibilidadEmpresarialDelegate, new object[] {
                        wsFactibilidadEmpresarialRQ}, this.onEndgetFactibilidadEmpresarialDelegate, this.ongetFactibilidadEmpresarialCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Lite.ServiceFactibilidadEmpresarial.WsFactibilidadEmpresarialPortType CreateChannel() {
            return new WsFactibilidadEmpresarialPortTypeClientChannel(this);
        }
        
        private class WsFactibilidadEmpresarialPortTypeClientChannel : ChannelBase<Lite.ServiceFactibilidadEmpresarial.WsFactibilidadEmpresarialPortType>, Lite.ServiceFactibilidadEmpresarial.WsFactibilidadEmpresarialPortType {
            
            public WsFactibilidadEmpresarialPortTypeClientChannel(System.ServiceModel.ClientBase<Lite.ServiceFactibilidadEmpresarial.WsFactibilidadEmpresarialPortType> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BegingetFactibilidadEmpresarial(Lite.ServiceFactibilidadEmpresarial.getFactibilidadEmpresarialRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("getFactibilidadEmpresarial", _args, callback, asyncState);
                return _result;
            }
            
            public Lite.ServiceFactibilidadEmpresarial.getFactibilidadEmpresarialResponse EndgetFactibilidadEmpresarial(System.IAsyncResult result) {
                object[] _args = new object[0];
                Lite.ServiceFactibilidadEmpresarial.getFactibilidadEmpresarialResponse _result = ((Lite.ServiceFactibilidadEmpresarial.getFactibilidadEmpresarialResponse)(base.EndInvoke("getFactibilidadEmpresarial", _args, result)));
                return _result;
            }
        }
    }
}
