//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18063
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace Lite.ServiceEliminaCliente {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.grr.net.fv/svc", ConfigurationName="ServiceEliminaCliente.WsEliminaUbicacionClienteFVPortType")]
    public interface WsEliminaUbicacionClienteFVPortType {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:eliminaUbicacionClienteFV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BegineliminaUbicacionClienteFV(Lite.ServiceEliminaCliente.eliminaUbicacionClienteFVRequest request, System.AsyncCallback callback, object asyncState);
        
        Lite.ServiceEliminaCliente.eliminaUbicacionClienteFVResponse EndeliminaUbicacionClienteFV(System.IAsyncResult result);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="wsEliminaUbicacionClienteFV-RQ-Type", Namespace="http://www.grr.net.fv/gis")]
    public partial class wsEliminaUbicacionClienteFVRQType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numero_cuentaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string numero_cuenta {
            get {
                return this.numero_cuentaField;
            }
            set {
                this.numero_cuentaField = value;
                this.RaisePropertyChanged("numero_cuenta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.grr.net.fv/gis")]
    public partial class detallerespuestatype : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fechaRespuestaField;
        
        private string codigoRespuestaField;
        
        private string codigoErrorField;
        
        private string descripcionErrorField;
        
        private string mensajeErrorField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FechaRespuesta {
            get {
                return this.fechaRespuestaField;
            }
            set {
                this.fechaRespuestaField = value;
                this.RaisePropertyChanged("FechaRespuesta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CodigoRespuesta {
            get {
                return this.codigoRespuestaField;
            }
            set {
                this.codigoRespuestaField = value;
                this.RaisePropertyChanged("CodigoRespuesta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CodigoError {
            get {
                return this.codigoErrorField;
            }
            set {
                this.codigoErrorField = value;
                this.RaisePropertyChanged("CodigoError");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DescripcionError {
            get {
                return this.descripcionErrorField;
            }
            set {
                this.descripcionErrorField = value;
                this.RaisePropertyChanged("DescripcionError");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string MensajeError {
            get {
                return this.mensajeErrorField;
            }
            set {
                this.mensajeErrorField = value;
                this.RaisePropertyChanged("MensajeError");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.grr.net.fv/gis")]
    public partial class InfoCliente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string estadoField;
        
        private detallerespuestatype detalle_RespuestaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public detallerespuestatype Detalle_Respuesta {
            get {
                return this.detalle_RespuestaField;
            }
            set {
                this.detalle_RespuestaField = value;
                this.RaisePropertyChanged("Detalle_Respuesta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class eliminaUbicacionClienteFVRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wsEliminaUbicacionClienteFV-RQ", Namespace="http://www.grr.net.fv/gis", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("wsEliminaUbicacionClienteFV-RQ")]
        public Lite.ServiceEliminaCliente.wsEliminaUbicacionClienteFVRQType wsEliminaUbicacionClienteFVRQ;
        
        public eliminaUbicacionClienteFVRequest() {
        }
        
        public eliminaUbicacionClienteFVRequest(Lite.ServiceEliminaCliente.wsEliminaUbicacionClienteFVRQType wsEliminaUbicacionClienteFVRQ) {
            this.wsEliminaUbicacionClienteFVRQ = wsEliminaUbicacionClienteFVRQ;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class eliminaUbicacionClienteFVResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wsEliminaUbicacionClienteFV-RS", Namespace="http://www.grr.net.fv/gis", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("wsEliminaUbicacionClienteFV-RS")]
        public Lite.ServiceEliminaCliente.InfoCliente wsEliminaUbicacionClienteFVRS;
        
        public eliminaUbicacionClienteFVResponse() {
        }
        
        public eliminaUbicacionClienteFVResponse(Lite.ServiceEliminaCliente.InfoCliente wsEliminaUbicacionClienteFVRS) {
            this.wsEliminaUbicacionClienteFVRS = wsEliminaUbicacionClienteFVRS;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WsEliminaUbicacionClienteFVPortTypeChannel : Lite.ServiceEliminaCliente.WsEliminaUbicacionClienteFVPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class eliminaUbicacionClienteFVCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public eliminaUbicacionClienteFVCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Lite.ServiceEliminaCliente.eliminaUbicacionClienteFVResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Lite.ServiceEliminaCliente.eliminaUbicacionClienteFVResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsEliminaUbicacionClienteFVPortTypeClient : System.ServiceModel.ClientBase<Lite.ServiceEliminaCliente.WsEliminaUbicacionClienteFVPortType>, Lite.ServiceEliminaCliente.WsEliminaUbicacionClienteFVPortType {
        
        private BeginOperationDelegate onBegineliminaUbicacionClienteFVDelegate;
        
        private EndOperationDelegate onEndeliminaUbicacionClienteFVDelegate;
        
        private System.Threading.SendOrPostCallback oneliminaUbicacionClienteFVCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public WsEliminaUbicacionClienteFVPortTypeClient() {
        }
        
        public WsEliminaUbicacionClienteFVPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsEliminaUbicacionClienteFVPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsEliminaUbicacionClienteFVPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsEliminaUbicacionClienteFVPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("No se puede establecer el objeto CookieContainer. Asegúrese de que el enlace cont" +
                            "iene un objeto HttpCookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<eliminaUbicacionClienteFVCompletedEventArgs> eliminaUbicacionClienteFVCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Lite.ServiceEliminaCliente.WsEliminaUbicacionClienteFVPortType.BegineliminaUbicacionClienteFV(Lite.ServiceEliminaCliente.eliminaUbicacionClienteFVRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegineliminaUbicacionClienteFV(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lite.ServiceEliminaCliente.eliminaUbicacionClienteFVResponse Lite.ServiceEliminaCliente.WsEliminaUbicacionClienteFVPortType.EndeliminaUbicacionClienteFV(System.IAsyncResult result) {
            return base.Channel.EndeliminaUbicacionClienteFV(result);
        }
        
        private System.IAsyncResult OnBegineliminaUbicacionClienteFV(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Lite.ServiceEliminaCliente.eliminaUbicacionClienteFVRequest request = ((Lite.ServiceEliminaCliente.eliminaUbicacionClienteFVRequest)(inValues[0]));
            return ((Lite.ServiceEliminaCliente.WsEliminaUbicacionClienteFVPortType)(this)).BegineliminaUbicacionClienteFV(request, callback, asyncState);
        }
        
        private object[] OnEndeliminaUbicacionClienteFV(System.IAsyncResult result) {
            Lite.ServiceEliminaCliente.eliminaUbicacionClienteFVResponse retVal = ((Lite.ServiceEliminaCliente.WsEliminaUbicacionClienteFVPortType)(this)).EndeliminaUbicacionClienteFV(result);
            return new object[] {
                    retVal};
        }
        
        private void OneliminaUbicacionClienteFVCompleted(object state) {
            if ((this.eliminaUbicacionClienteFVCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.eliminaUbicacionClienteFVCompleted(this, new eliminaUbicacionClienteFVCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void eliminaUbicacionClienteFVAsync(Lite.ServiceEliminaCliente.eliminaUbicacionClienteFVRequest request) {
            this.eliminaUbicacionClienteFVAsync(request, null);
        }
        
        public void eliminaUbicacionClienteFVAsync(Lite.ServiceEliminaCliente.eliminaUbicacionClienteFVRequest request, object userState) {
            if ((this.onBegineliminaUbicacionClienteFVDelegate == null)) {
                this.onBegineliminaUbicacionClienteFVDelegate = new BeginOperationDelegate(this.OnBegineliminaUbicacionClienteFV);
            }
            if ((this.onEndeliminaUbicacionClienteFVDelegate == null)) {
                this.onEndeliminaUbicacionClienteFVDelegate = new EndOperationDelegate(this.OnEndeliminaUbicacionClienteFV);
            }
            if ((this.oneliminaUbicacionClienteFVCompletedDelegate == null)) {
                this.oneliminaUbicacionClienteFVCompletedDelegate = new System.Threading.SendOrPostCallback(this.OneliminaUbicacionClienteFVCompleted);
            }
            base.InvokeAsync(this.onBegineliminaUbicacionClienteFVDelegate, new object[] {
                        request}, this.onEndeliminaUbicacionClienteFVDelegate, this.oneliminaUbicacionClienteFVCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Lite.ServiceEliminaCliente.WsEliminaUbicacionClienteFVPortType CreateChannel() {
            return new WsEliminaUbicacionClienteFVPortTypeClientChannel(this);
        }
        
        private class WsEliminaUbicacionClienteFVPortTypeClientChannel : ChannelBase<Lite.ServiceEliminaCliente.WsEliminaUbicacionClienteFVPortType>, Lite.ServiceEliminaCliente.WsEliminaUbicacionClienteFVPortType {
            
            public WsEliminaUbicacionClienteFVPortTypeClientChannel(System.ServiceModel.ClientBase<Lite.ServiceEliminaCliente.WsEliminaUbicacionClienteFVPortType> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BegineliminaUbicacionClienteFV(Lite.ServiceEliminaCliente.eliminaUbicacionClienteFVRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("eliminaUbicacionClienteFV", _args, callback, asyncState);
                return _result;
            }
            
            public Lite.ServiceEliminaCliente.eliminaUbicacionClienteFVResponse EndeliminaUbicacionClienteFV(System.IAsyncResult result) {
                object[] _args = new object[0];
                Lite.ServiceEliminaCliente.eliminaUbicacionClienteFVResponse _result = null;
                try{
                 _result = ((Lite.ServiceEliminaCliente.eliminaUbicacionClienteFVResponse)(base.EndInvoke("eliminaUbicacionClienteFV", _args, result)));
                }
                catch { }
                return _result;
            }
        }
    }
}
