//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace Lite.ServiceFactibilidadResidencial {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.grr.net.fv/svc", ConfigurationName="ServiceFactibilidadResidencial.WsFactibilidadResidencialPortType")]
    public interface WsFactibilidadResidencialPortType {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:getFactibilidadResidencial", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BegingetFactibilidadResidencial(Lite.ServiceFactibilidadResidencial.getFactibilidadResidencialRequest request, System.AsyncCallback callback, object asyncState);
        
        Lite.ServiceFactibilidadResidencial.getFactibilidadResidencialResponse EndgetFactibilidadResidencial(System.IAsyncResult result);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="wsFactibilidadResidencial-RQ-Type", Namespace="http://www.grr.net.fv/gis")]
    public partial class wsFactibilidadResidencialRQType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string latitudField;
        
        private string longitudField;
        
        private string coloniaField;
        
        private string cpField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string latitud {
            get {
                return this.latitudField;
            }
            set {
                this.latitudField = value;
                this.RaisePropertyChanged("latitud");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string longitud {
            get {
                return this.longitudField;
            }
            set {
                this.longitudField = value;
                this.RaisePropertyChanged("longitud");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string colonia {
            get {
                return this.coloniaField;
            }
            set {
                this.coloniaField = value;
                this.RaisePropertyChanged("colonia");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string cp {
            get {
                return this.cpField;
            }
            set {
                this.cpField = value;
                this.RaisePropertyChanged("cp");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.grr.net.fv/gis")]
    public partial class detalleRespuestaType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mensajeTransaccionField;
        
        private string codigoErrorField;
        
        private string descripcionErrorField;
        
        private string mensajeErrorField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MensajeTransaccion {
            get {
                return this.mensajeTransaccionField;
            }
            set {
                this.mensajeTransaccionField = value;
                this.RaisePropertyChanged("MensajeTransaccion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CodigoError {
            get {
                return this.codigoErrorField;
            }
            set {
                this.codigoErrorField = value;
                this.RaisePropertyChanged("CodigoError");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DescripcionError {
            get {
                return this.descripcionErrorField;
            }
            set {
                this.descripcionErrorField = value;
                this.RaisePropertyChanged("DescripcionError");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MensajeError {
            get {
                return this.mensajeErrorField;
            }
            set {
                this.mensajeErrorField = value;
                this.RaisePropertyChanged("MensajeError");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="wsFactibilidadResidencial-RS-Type", Namespace="http://www.grr.net.fv/gis")]
    public partial class wsFactibilidadResidencialRSType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string factibilidadField;
        
        private string comentarioField;
        
        private string domicilioField;
        
        private string cluster_totalplayField;
        
        private string region_totalplayField;
        
        private string ciudad_totalplayField;
        
        private string distrito_totalplayField;
        
        private string zona_totalplayField;
        
        private detalleRespuestaType detalleRespuestaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string factibilidad {
            get {
                return this.factibilidadField;
            }
            set {
                this.factibilidadField = value;
                this.RaisePropertyChanged("factibilidad");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string comentario {
            get {
                return this.comentarioField;
            }
            set {
                this.comentarioField = value;
                this.RaisePropertyChanged("comentario");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string domicilio {
            get {
                return this.domicilioField;
            }
            set {
                this.domicilioField = value;
                this.RaisePropertyChanged("domicilio");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string cluster_totalplay {
            get {
                return this.cluster_totalplayField;
            }
            set {
                this.cluster_totalplayField = value;
                this.RaisePropertyChanged("cluster_totalplay");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string region_totalplay {
            get {
                return this.region_totalplayField;
            }
            set {
                this.region_totalplayField = value;
                this.RaisePropertyChanged("region_totalplay");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ciudad_totalplay {
            get {
                return this.ciudad_totalplayField;
            }
            set {
                this.ciudad_totalplayField = value;
                this.RaisePropertyChanged("ciudad_totalplay");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string distrito_totalplay {
            get {
                return this.distrito_totalplayField;
            }
            set {
                this.distrito_totalplayField = value;
                this.RaisePropertyChanged("distrito_totalplay");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string zona_totalplay {
            get {
                return this.zona_totalplayField;
            }
            set {
                this.zona_totalplayField = value;
                this.RaisePropertyChanged("zona_totalplay");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public detalleRespuestaType detalleRespuesta {
            get {
                return this.detalleRespuestaField;
            }
            set {
                this.detalleRespuestaField = value;
                this.RaisePropertyChanged("detalleRespuesta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFactibilidadResidencialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wsFactibilidadResidencial-RQ", Namespace="http://www.grr.net.fv/gis", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("wsFactibilidadResidencial-RQ")]
        public Lite.ServiceFactibilidadResidencial.wsFactibilidadResidencialRQType wsFactibilidadResidencialRQ;
        
        public getFactibilidadResidencialRequest() {
        }
        
        public getFactibilidadResidencialRequest(Lite.ServiceFactibilidadResidencial.wsFactibilidadResidencialRQType wsFactibilidadResidencialRQ) {
            this.wsFactibilidadResidencialRQ = wsFactibilidadResidencialRQ;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFactibilidadResidencialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wsFactibilidadResidencial-RS", Namespace="http://www.grr.net.fv/gis", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("wsFactibilidadResidencial-RS")]
        public Lite.ServiceFactibilidadResidencial.wsFactibilidadResidencialRSType wsFactibilidadResidencialRS;
        
        public getFactibilidadResidencialResponse() {
        }
        
        public getFactibilidadResidencialResponse(Lite.ServiceFactibilidadResidencial.wsFactibilidadResidencialRSType wsFactibilidadResidencialRS) {
            this.wsFactibilidadResidencialRS = wsFactibilidadResidencialRS;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WsFactibilidadResidencialPortTypeChannel : Lite.ServiceFactibilidadResidencial.WsFactibilidadResidencialPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getFactibilidadResidencialCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getFactibilidadResidencialCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Lite.ServiceFactibilidadResidencial.wsFactibilidadResidencialRSType Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Lite.ServiceFactibilidadResidencial.wsFactibilidadResidencialRSType)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsFactibilidadResidencialPortTypeClient : System.ServiceModel.ClientBase<Lite.ServiceFactibilidadResidencial.WsFactibilidadResidencialPortType>, Lite.ServiceFactibilidadResidencial.WsFactibilidadResidencialPortType {
        
        private BeginOperationDelegate onBegingetFactibilidadResidencialDelegate;
        
        private EndOperationDelegate onEndgetFactibilidadResidencialDelegate;
        
        private System.Threading.SendOrPostCallback ongetFactibilidadResidencialCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public WsFactibilidadResidencialPortTypeClient() {
        }
        
        public WsFactibilidadResidencialPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsFactibilidadResidencialPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsFactibilidadResidencialPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsFactibilidadResidencialPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("No se puede establecer el objeto CookieContainer. Asegúrese de que el enlace cont" +
                            "iene un objeto HttpCookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<getFactibilidadResidencialCompletedEventArgs> getFactibilidadResidencialCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Lite.ServiceFactibilidadResidencial.WsFactibilidadResidencialPortType.BegingetFactibilidadResidencial(Lite.ServiceFactibilidadResidencial.getFactibilidadResidencialRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetFactibilidadResidencial(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BegingetFactibilidadResidencial(Lite.ServiceFactibilidadResidencial.wsFactibilidadResidencialRQType wsFactibilidadResidencialRQ, System.AsyncCallback callback, object asyncState) {
            Lite.ServiceFactibilidadResidencial.getFactibilidadResidencialRequest inValue = new Lite.ServiceFactibilidadResidencial.getFactibilidadResidencialRequest();
            inValue.wsFactibilidadResidencialRQ = wsFactibilidadResidencialRQ;
            return ((Lite.ServiceFactibilidadResidencial.WsFactibilidadResidencialPortType)(this)).BegingetFactibilidadResidencial(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lite.ServiceFactibilidadResidencial.getFactibilidadResidencialResponse Lite.ServiceFactibilidadResidencial.WsFactibilidadResidencialPortType.EndgetFactibilidadResidencial(System.IAsyncResult result) {
            return base.Channel.EndgetFactibilidadResidencial(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private Lite.ServiceFactibilidadResidencial.wsFactibilidadResidencialRSType EndgetFactibilidadResidencial(System.IAsyncResult result) {
            Lite.ServiceFactibilidadResidencial.getFactibilidadResidencialResponse retVal = ((Lite.ServiceFactibilidadResidencial.WsFactibilidadResidencialPortType)(this)).EndgetFactibilidadResidencial(result);
            return retVal.wsFactibilidadResidencialRS;
        }
        
        private System.IAsyncResult OnBegingetFactibilidadResidencial(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Lite.ServiceFactibilidadResidencial.wsFactibilidadResidencialRQType wsFactibilidadResidencialRQ = ((Lite.ServiceFactibilidadResidencial.wsFactibilidadResidencialRQType)(inValues[0]));
            return this.BegingetFactibilidadResidencial(wsFactibilidadResidencialRQ, callback, asyncState);
        }
        
        private object[] OnEndgetFactibilidadResidencial(System.IAsyncResult result) {
            Lite.ServiceFactibilidadResidencial.wsFactibilidadResidencialRSType retVal = this.EndgetFactibilidadResidencial(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetFactibilidadResidencialCompleted(object state) {
            if ((this.getFactibilidadResidencialCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getFactibilidadResidencialCompleted(this, new getFactibilidadResidencialCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getFactibilidadResidencialAsync(Lite.ServiceFactibilidadResidencial.wsFactibilidadResidencialRQType wsFactibilidadResidencialRQ) {
            this.getFactibilidadResidencialAsync(wsFactibilidadResidencialRQ, null);
        }
        
        public void getFactibilidadResidencialAsync(Lite.ServiceFactibilidadResidencial.wsFactibilidadResidencialRQType wsFactibilidadResidencialRQ, object userState) {
            if ((this.onBegingetFactibilidadResidencialDelegate == null)) {
                this.onBegingetFactibilidadResidencialDelegate = new BeginOperationDelegate(this.OnBegingetFactibilidadResidencial);
            }
            if ((this.onEndgetFactibilidadResidencialDelegate == null)) {
                this.onEndgetFactibilidadResidencialDelegate = new EndOperationDelegate(this.OnEndgetFactibilidadResidencial);
            }
            if ((this.ongetFactibilidadResidencialCompletedDelegate == null)) {
                this.ongetFactibilidadResidencialCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetFactibilidadResidencialCompleted);
            }
            base.InvokeAsync(this.onBegingetFactibilidadResidencialDelegate, new object[] {
                        wsFactibilidadResidencialRQ}, this.onEndgetFactibilidadResidencialDelegate, this.ongetFactibilidadResidencialCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Lite.ServiceFactibilidadResidencial.WsFactibilidadResidencialPortType CreateChannel() {
            return new WsFactibilidadResidencialPortTypeClientChannel(this);
        }
        
        private class WsFactibilidadResidencialPortTypeClientChannel : ChannelBase<Lite.ServiceFactibilidadResidencial.WsFactibilidadResidencialPortType>, Lite.ServiceFactibilidadResidencial.WsFactibilidadResidencialPortType {
            
            public WsFactibilidadResidencialPortTypeClientChannel(System.ServiceModel.ClientBase<Lite.ServiceFactibilidadResidencial.WsFactibilidadResidencialPortType> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BegingetFactibilidadResidencial(Lite.ServiceFactibilidadResidencial.getFactibilidadResidencialRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("getFactibilidadResidencial", _args, callback, asyncState);
                return _result;
            }
            
            public Lite.ServiceFactibilidadResidencial.getFactibilidadResidencialResponse EndgetFactibilidadResidencial(System.IAsyncResult result) {
                object[] _args = new object[0];
                Lite.ServiceFactibilidadResidencial.getFactibilidadResidencialResponse _result = ((Lite.ServiceFactibilidadResidencial.getFactibilidadResidencialResponse)(base.EndInvoke("getFactibilidadResidencial", _args, result)));
                return _result;
            }
        }
    }
}
