//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace Lite.ServiceEliminaIncidente
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://www.grr.net.fv/svc", ConfigurationName = "ServiceEliminaIncidente.WsEliminaUbicacionIncidentePortType")]
    public interface WsEliminaUbicacionIncidentePortType
    {

        [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "urn:eliminaUbicacionIncidente", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.IAsyncResult BegineliminaUbicacionIncidente(Lite.ServiceEliminaIncidente.eliminaUbicacionIncidenteRequest request, System.AsyncCallback callback, object asyncState);

        Lite.ServiceEliminaIncidente.eliminaUbicacionIncidenteResponse EndeliminaUbicacionIncidente(System.IAsyncResult result);
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "wsEliminaUbicacionIncidente-RQ-Type", Namespace = "http://www.grr.net.fv/gis")]
    public partial class wsEliminaUbicacionIncidenteRQType : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string folioField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 0)]
        public string folio
        {
            get
            {
                return this.folioField;
            }
            set
            {
                this.folioField = value;
                this.RaisePropertyChanged("folio");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.grr.net.fv/gis")]
    public partial class detallerespuestatype : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string fechaRespuestaField;

        private string codigoRespuestaField;

        private string codigoErrorField;

        private string descripcionErrorField;

        private string mensajeErrorField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string FechaRespuesta
        {
            get
            {
                return this.fechaRespuestaField;
            }
            set
            {
                this.fechaRespuestaField = value;
                this.RaisePropertyChanged("FechaRespuesta");
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string CodigoRespuesta
        {
            get
            {
                return this.codigoRespuestaField;
            }
            set
            {
                this.codigoRespuestaField = value;
                this.RaisePropertyChanged("CodigoRespuesta");
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string CodigoError
        {
            get
            {
                return this.codigoErrorField;
            }
            set
            {
                this.codigoErrorField = value;
                this.RaisePropertyChanged("CodigoError");
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string DescripcionError
        {
            get
            {
                return this.descripcionErrorField;
            }
            set
            {
                this.descripcionErrorField = value;
                this.RaisePropertyChanged("DescripcionError");
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string MensajeError
        {
            get
            {
                return this.mensajeErrorField;
            }
            set
            {
                this.mensajeErrorField = value;
                this.RaisePropertyChanged("MensajeError");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.grr.net.fv/gis")]
    public partial class InfoIncidente : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string estadoField;

        private detallerespuestatype detalle_RespuestaField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public detallerespuestatype Detalle_Respuesta
        {
            get
            {
                return this.detalle_RespuestaField;
            }
            set
            {
                this.detalle_RespuestaField = value;
                this.RaisePropertyChanged("Detalle_Respuesta");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class eliminaUbicacionIncidenteRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "wsEliminaUbicacionIncidente-RQ", Namespace = "http://www.grr.net.fv/gis", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("wsEliminaUbicacionIncidente-RQ")]
        public Lite.ServiceEliminaIncidente.wsEliminaUbicacionIncidenteRQType wsEliminaUbicacionIncidenteRQ;

        public eliminaUbicacionIncidenteRequest()
        {
        }

        public eliminaUbicacionIncidenteRequest(Lite.ServiceEliminaIncidente.wsEliminaUbicacionIncidenteRQType wsEliminaUbicacionIncidenteRQ)
        {
            this.wsEliminaUbicacionIncidenteRQ = wsEliminaUbicacionIncidenteRQ;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class eliminaUbicacionIncidenteResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "wsEliminaUbicacionIncidente-RS", Namespace = "http://www.grr.net.fv/gis", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("wsEliminaUbicacionIncidente-RS")]
        public Lite.ServiceEliminaIncidente.InfoIncidente wsEliminaUbicacionIncidenteRS;

        public eliminaUbicacionIncidenteResponse()
        {
        }

        public eliminaUbicacionIncidenteResponse(Lite.ServiceEliminaIncidente.InfoIncidente wsEliminaUbicacionIncidenteRS)
        {
            this.wsEliminaUbicacionIncidenteRS = wsEliminaUbicacionIncidenteRS;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WsEliminaUbicacionIncidentePortTypeChannel : Lite.ServiceEliminaIncidente.WsEliminaUbicacionIncidentePortType, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class eliminaUbicacionIncidenteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        public eliminaUbicacionIncidenteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        public Lite.ServiceEliminaIncidente.eliminaUbicacionIncidenteResponse Result
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((Lite.ServiceEliminaIncidente.eliminaUbicacionIncidenteResponse)(this.results[0]));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsEliminaUbicacionIncidentePortTypeClient : System.ServiceModel.ClientBase<Lite.ServiceEliminaIncidente.WsEliminaUbicacionIncidentePortType>, Lite.ServiceEliminaIncidente.WsEliminaUbicacionIncidentePortType
    {

        private BeginOperationDelegate onBegineliminaUbicacionIncidenteDelegate;

        private EndOperationDelegate onEndeliminaUbicacionIncidenteDelegate;

        private System.Threading.SendOrPostCallback oneliminaUbicacionIncidenteCompletedDelegate;

        private BeginOperationDelegate onBeginOpenDelegate;

        private EndOperationDelegate onEndOpenDelegate;

        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;

        private BeginOperationDelegate onBeginCloseDelegate;

        private EndOperationDelegate onEndCloseDelegate;

        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;

        public WsEliminaUbicacionIncidentePortTypeClient()
        {
        }

        public WsEliminaUbicacionIncidentePortTypeClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public WsEliminaUbicacionIncidentePortTypeClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public WsEliminaUbicacionIncidentePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public WsEliminaUbicacionIncidentePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        public System.Net.CookieContainer CookieContainer
        {
            get
            {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null))
                {
                    return httpCookieContainerManager.CookieContainer;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null))
                {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else
                {
                    throw new System.InvalidOperationException("No se puede establecer el objeto CookieContainer. Asegúrese de que el enlace cont" +
                            "iene un objeto HttpCookieContainerBindingElement.");
                }
            }
        }

        public event System.EventHandler<eliminaUbicacionIncidenteCompletedEventArgs> eliminaUbicacionIncidenteCompleted;

        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;

        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Lite.ServiceEliminaIncidente.WsEliminaUbicacionIncidentePortType.BegineliminaUbicacionIncidente(Lite.ServiceEliminaIncidente.eliminaUbicacionIncidenteRequest request, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BegineliminaUbicacionIncidente(request, callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lite.ServiceEliminaIncidente.eliminaUbicacionIncidenteResponse Lite.ServiceEliminaIncidente.WsEliminaUbicacionIncidentePortType.EndeliminaUbicacionIncidente(System.IAsyncResult result)
        {
            return base.Channel.EndeliminaUbicacionIncidente(result);
        }

        private System.IAsyncResult OnBegineliminaUbicacionIncidente(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            Lite.ServiceEliminaIncidente.eliminaUbicacionIncidenteRequest request = ((Lite.ServiceEliminaIncidente.eliminaUbicacionIncidenteRequest)(inValues[0]));
            return ((Lite.ServiceEliminaIncidente.WsEliminaUbicacionIncidentePortType)(this)).BegineliminaUbicacionIncidente(request, callback, asyncState);
        }

        private object[] OnEndeliminaUbicacionIncidente(System.IAsyncResult result)
        {
            Lite.ServiceEliminaIncidente.eliminaUbicacionIncidenteResponse retVal = ((Lite.ServiceEliminaIncidente.WsEliminaUbicacionIncidentePortType)(this)).EndeliminaUbicacionIncidente(result);
            return new object[] {
                    retVal};
        }

        private void OneliminaUbicacionIncidenteCompleted(object state)
        {
            if ((this.eliminaUbicacionIncidenteCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.eliminaUbicacionIncidenteCompleted(this, new eliminaUbicacionIncidenteCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        public void eliminaUbicacionIncidenteAsync(Lite.ServiceEliminaIncidente.eliminaUbicacionIncidenteRequest request)
        {
            this.eliminaUbicacionIncidenteAsync(request, null);
        }

        public void eliminaUbicacionIncidenteAsync(Lite.ServiceEliminaIncidente.eliminaUbicacionIncidenteRequest request, object userState)
        {
            if ((this.onBegineliminaUbicacionIncidenteDelegate == null))
            {
                this.onBegineliminaUbicacionIncidenteDelegate = new BeginOperationDelegate(this.OnBegineliminaUbicacionIncidente);
            }
            if ((this.onEndeliminaUbicacionIncidenteDelegate == null))
            {
                this.onEndeliminaUbicacionIncidenteDelegate = new EndOperationDelegate(this.OnEndeliminaUbicacionIncidente);
            }
            if ((this.oneliminaUbicacionIncidenteCompletedDelegate == null))
            {
                this.oneliminaUbicacionIncidenteCompletedDelegate = new System.Threading.SendOrPostCallback(this.OneliminaUbicacionIncidenteCompleted);
            }
            base.InvokeAsync(this.onBegineliminaUbicacionIncidenteDelegate, new object[] {
                        request}, this.onEndeliminaUbicacionIncidenteDelegate, this.oneliminaUbicacionIncidenteCompletedDelegate, userState);
        }

        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }

        private object[] OnEndOpen(System.IAsyncResult result)
        {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }

        private void OnOpenCompleted(object state)
        {
            if ((this.OpenCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }

        public void OpenAsync()
        {
            this.OpenAsync(null);
        }

        public void OpenAsync(object userState)
        {
            if ((this.onBeginOpenDelegate == null))
            {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null))
            {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null))
            {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }

        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }

        private object[] OnEndClose(System.IAsyncResult result)
        {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }

        private void OnCloseCompleted(object state)
        {
            if ((this.CloseCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }

        public void CloseAsync()
        {
            this.CloseAsync(null);
        }

        public void CloseAsync(object userState)
        {
            if ((this.onBeginCloseDelegate == null))
            {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null))
            {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null))
            {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }

        protected override Lite.ServiceEliminaIncidente.WsEliminaUbicacionIncidentePortType CreateChannel()
        {
            return new WsEliminaUbicacionIncidentePortTypeClientChannel(this);
        }

        private class WsEliminaUbicacionIncidentePortTypeClientChannel : ChannelBase<Lite.ServiceEliminaIncidente.WsEliminaUbicacionIncidentePortType>, Lite.ServiceEliminaIncidente.WsEliminaUbicacionIncidentePortType
        {

            public WsEliminaUbicacionIncidentePortTypeClientChannel(System.ServiceModel.ClientBase<Lite.ServiceEliminaIncidente.WsEliminaUbicacionIncidentePortType> client) :
                base(client)
            {
            }

            public System.IAsyncResult BegineliminaUbicacionIncidente(Lite.ServiceEliminaIncidente.eliminaUbicacionIncidenteRequest request, System.AsyncCallback callback, object asyncState)
            {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("eliminaUbicacionIncidente", _args, callback, asyncState);
                return _result;
            }

            public Lite.ServiceEliminaIncidente.eliminaUbicacionIncidenteResponse EndeliminaUbicacionIncidente(System.IAsyncResult result)
            {
                object[] _args = new object[0];
                Lite.ServiceEliminaIncidente.eliminaUbicacionIncidenteResponse _result = ((Lite.ServiceEliminaIncidente.eliminaUbicacionIncidenteResponse)(base.EndInvoke("eliminaUbicacionIncidente", _args, result)));
                return _result;
            }
        }
    }
}
